<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_48aygC9-EfCqJOVmptBMqg" name="Processo" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_48aygS9-EfCqJOVmptBMqg" name="SugestaoMelhoria" displayName="Sugestão Melhoria">
      <elements xmi:type="process:Lane" xmi:id="_48aygi9-EfCqJOVmptBMqg" name="Colaborador" actor="_SeTI8C-NEfC1UoIdMei-qg">
        <elements xmi:type="process:StartEvent" xmi:id="_48aygy9-EfCqJOVmptBMqg" name="Start" outgoing="_ar0X4zQKEfC8CYkRjdP_Iw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_48ayhC9-EfCqJOVmptBMqg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_48ayhS9-EfCqJOVmptBMqg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_48ayhi9-EfCqJOVmptBMqg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4zYp8C-MEfC1UoIdMei-qg" name="Ajustar Melhoria" outgoing="_EcSLQC-DEfC1UoIdMei-qg" incoming="_XYuAEC-DEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_48ayiC9-EfCqJOVmptBMqg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_48ayiS9-EfCqJOVmptBMqg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_48ayii9-EfCqJOVmptBMqg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_48bZkC9-EfCqJOVmptBMqg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_48bZkS9-EfCqJOVmptBMqg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_48bZki9-EfCqJOVmptBMqg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_48bZky9-EfCqJOVmptBMqg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_48bZlC9-EfCqJOVmptBMqg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4zZ4GS-MEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_qZlokDQbEfCDrJ8UxzY4jg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4zZ4GC-MEfC1UoIdMei-qg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4zZ4Gy-MEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_15RnsDQKEfC8CYkRjdP_Iw" name="Proposta de melhoria" outgoing="_lrOEsDQKEfC8CYkRjdP_Iw" incoming="_ar0X4zQKEfC8CYkRjdP_Iw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_arzw0jQKEfC8CYkRjdP_Iw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_arzw0TQKEfC8CYkRjdP_Iw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_arzw0zQKEfC8CYkRjdP_Iw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_KooVMzQXEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_KooVNDQXEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KooVNTQXEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_KooVNjQXEfCDrJ8UxzY4jg" name="melhoriaInput.oQueFazer" content="     ?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_KooVODQXEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_KooVOTQXEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_KooVOjQXEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KooVOzQXEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_KooVPDQXEfCDrJ8UxzY4jg" name="melhoriaInput.comoFazer" content="     ?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_KooVPjQXEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_KooVPzQXEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_KooVQDQXEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KooVQTQXEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_KooVQjQXEfCDrJ8UxzY4jg" name="melhoriaInput.ondeFazer" content="     ?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_KooVRDQXEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_KooVRTQXEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_KooVRjQXEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KooVRzQXEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_KooVSDQXEfCDrJ8UxzY4jg" name="melhoriaInput.descricaoFazer" content="     ?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_KooVSjQXEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_18UE6jQbEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_18UE6zQbEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_18UE7DQbEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_18UE7TQbEfCDrJ8UxzY4jg" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_18UE7jQbEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_18UE7zQbEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_18UE8DQbEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_18UE8TQbEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_18UE8jQbEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_18UE8zQbEfCDrJ8UxzY4jg" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_18UE9DQbEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_18UE9TQbEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_18UE9jQbEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_18UE9zQbEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_18UE-DQbEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_18UE-TQbEfCDrJ8UxzY4jg" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_18UE-jQbEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_18UE-zQbEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_18UE_DQbEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_18UE_TQbEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_18UE_jQbEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_18UE_zQbEfCDrJ8UxzY4jg" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_18UFADQbEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_18UFATQbEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_18UFAjQbEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_18UFAzQbEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_18UFBDQbEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_18UFBTQbEfCDrJ8UxzY4jg" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_18UFBjQbEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_18UFBzQbEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_18UFCDQbEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_18UFCTQbEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_18UFCjQbEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_18UFCzQbEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_18UFDDQbEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_18UFDTQbEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_arzw1DQKEfC8CYkRjdP_Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_arzw1TQKEfC8CYkRjdP_Iw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_arzw1jQKEfC8CYkRjdP_Iw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_arzw2DQKEfC8CYkRjdP_Iw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_arzw1zQKEfC8CYkRjdP_Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_15SOyTQKEfC8CYkRjdP_Iw">
            <targetForm xmi:type="expression:Expression" xmi:id="_15SOyjQKEfC8CYkRjdP_Iw" name="newForm" content="3dc76b08-7316-4ab4-9acc-16182cb7ae40" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_15SOyDQKEfC8CYkRjdP_Iw">
            <inputs xmi:type="process:ContractInput" xmi:id="_18UE4DQbEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_18UE4TQbEfCDrJ8UxzY4jg" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_18UE4jQbEfCDrJ8UxzY4jg" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_18UE4zQbEfCDrJ8UxzY4jg" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_18UE5DQbEfCDrJ8UxzY4jg" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_18UE5TQbEfCDrJ8UxzY4jg" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_18UE5jQbEfCDrJ8UxzY4jg" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_18UE5zQbEfCDrJ8UxzY4jg" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_18UE6DQbEfCDrJ8UxzY4jg" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_18UE6TQbEfCDrJ8UxzY4jg" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_15SOyzQKEfC8CYkRjdP_Iw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_-dUmkC-PEfC1UoIdMei-qg" name="Iniciador" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_-dUmkS-PEfC1UoIdMei-qg" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-dUmki-PEfC1UoIdMei-qg" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_-dUmky-PEfC1UoIdMei-qg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_eJCaIC9_EfCqJOVmptBMqg" name="Gestor" actor="_SeTI8C-NEfC1UoIdMei-qg">
        <elements xmi:type="process:Task" xmi:id="_E81TkC-DEfC1UoIdMei-qg" name="Deliberar e Aprovar Melhoria" outgoing="_VKRLgC-DEfC1UoIdMei-qg" incoming="_lrOEsDQKEfC8CYkRjdP_Iw _EcSLQC-DEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EcLdkS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EcLdkC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EcMEoC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfgzQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfhDQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfhTQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfhjQcEfCDrJ8UxzY4jg" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfhzQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfiDQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfiTQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfijQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfizQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfjDQcEfCDrJ8UxzY4jg" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfjTQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfjjQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfjzQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfkDQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfkTQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfkjQcEfCDrJ8UxzY4jg" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfkzQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhflDQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhflTQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfljQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhflzQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfmDQcEfCDrJ8UxzY4jg" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfmTQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfmjQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfmzQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfnDQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfnTQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfnjQcEfCDrJ8UxzY4jg" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfnzQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfoDQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfoTQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfojQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfozQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfpDQcEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfpTQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfpjQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EcMEoS-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EcMEoi-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EcMEoy-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EcMEpS-DEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EcMEpC-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_E8498C-DEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_alH00DQcEfCDrJ8UxzY4jg" name="AvaliacaoRequisicaoGestorForm" content="9261ac36-48f4-4d56-8a29-6e9a4c587978" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_E84W4S-DEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_AXg4cDQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4cTQcEfCDrJ8UxzY4jg" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4cjQcEfCDrJ8UxzY4jg" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4czQcEfCDrJ8UxzY4jg" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4dDQcEfCDrJ8UxzY4jg" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4dTQcEfCDrJ8UxzY4jg" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4djQcEfCDrJ8UxzY4jg" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_E8498i-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Wv7hwC-DEfC1UoIdMei-qg" name="Aprovada?" outgoing="_XYuAEC-DEfC1UoIdMei-qg _ZBq64C-DEfC1UoIdMei-qg _nSswgS-DEfC1UoIdMei-qg" incoming="_VKRLgC-DEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VKPWUS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VKPWUC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VKPWUi-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_b0KQoC-DEfC1UoIdMei-qg" name="Fim - Reprovada pelo Gestor" incoming="_ZBq64C-DEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_b0KQoi-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_b0KQoS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_b0KQoy-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_P_uHUC-FEfC1UoIdMei-qg" name="Comunica Colaborador" outgoing="_Sb8SIC-FEfC1UoIdMei-qg" incoming="_Pr7ooS-FEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pr5zcS-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pr5zcC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pr5zci-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pr5zcy-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pr5zdC-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pr5zdS-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pr6agS-FEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pr6agC-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_P_uuaS-FEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_qZlokTQbEfCDrJ8UxzY4jg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_P_uuaC-FEfC1UoIdMei-qg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_P_uuay-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Sb514C-FEfC1UoIdMei-qg" name="Melhoria Implantada" incoming="_Sb8SIC-FEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Sb6c8S-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Sb6c8C-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Sb6c8i-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_ZOVDkC-TEfC1UoIdMei-qg" name="Gestor" definitionId="bonita-actorfilter-initiator-manager" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_ZOVDkS-TEfC1UoIdMei-qg" definitionId="bonita-actorfilter-initiator-manager" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ZOVDki-TEfC1UoIdMei-qg" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_ZOVDky-TEfC1UoIdMei-qg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_eiGaYC9_EfCqJOVmptBMqg" name="Engenharia" actor="_VEfvIC-NEfC1UoIdMei-qg">
        <elements xmi:type="process:ServiceTask" xmi:id="_nSptMC-DEfC1UoIdMei-qg" name="Deliberar Relevancia da melhoria" outgoing="_pst74C-DEfC1UoIdMei-qg" incoming="_nSswgS-DEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nSqUQS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nSqUQC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nSqUQi-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nSqUQy-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nSq7UC-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nSq7US-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nSq7Uy-DEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nSq7Ui-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_svB2UC-DEfC1UoIdMei-qg" name="Aprovada Engenharia" outgoing="_rOnMcC-DEfC1UoIdMei-qg _4XxbEC-DEfC1UoIdMei-qg" incoming="_pst74C-DEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pssGsi-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pssGsS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pssGsy-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_vKE8cC-DEfC1UoIdMei-qg" name="Fim - Reprovada Engenharia" incoming="_rOnMcC-DEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ti0qwS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ti0qwC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ti1R0C-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AkXpEC-EEfC1UoIdMei-qg" name="Avaliar Viabilidade Técnica e Financeira" outgoing="_OFHRQC-EEfC1UoIdMei-qg" incoming="_APqkYC-EEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_APpWQS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_APpWQC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_APpWQi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUgDQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJUgTQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJUgjQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJUgzQdEfCDrJ8UxzY4jg" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJUhDQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJUhTQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUhjQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJUhzQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJUiDQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJUiTQdEfCDrJ8UxzY4jg" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJUijQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJUizQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUjDQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJUjTQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJUjjQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJUjzQdEfCDrJ8UxzY4jg" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJUkDQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJUkTQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUkjQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJUkzQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJUlDQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJUlTQdEfCDrJ8UxzY4jg" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJUljQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJUlzQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUmDQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7gDQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7gTQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7gjQdEfCDrJ8UxzY4jg" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7gzQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7hDQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7hTQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7hjQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7hzQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7iDQdEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7iTQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7ijQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7izQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7jDQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7jTQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7jjQdEfCDrJ8UxzY4jg" name="melhoriaInput.comentarioEngenharia" content="melhoriaInput?.comentarioEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7jzQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7kDQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComentarioEngenharia">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7kTQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7kjQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7kzQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7lDQdEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoEngenharia" content="melhoriaInput?.aprovacaoEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7lTQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7ljQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoEngenharia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7lzQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7mDQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7mTQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7mjQdEfCDrJ8UxzY4jg" name="melhoriaInput.ordemServicoRequisitos" content="melhoriaInput?.ordemServicoRequisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7mzQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7nDQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOrdemServicoRequisitos">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7nTQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7njQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7nzQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7oDQdEfCDrJ8UxzY4jg" name="melhoriaInput.requisitos" content="melhoriaInput?.requisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7oTQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7ojQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setRequisitos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7ozQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7pDQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7pTQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7pjQdEfCDrJ8UxzY4jg" name="melhoriaInput.analiseViabilidade" content="melhoriaInput?.analiseViabilidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7pzQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7qDQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAnaliseViabilidade">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7qTQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7qjQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7qzQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7rDQdEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoViabilidade" content="melhoriaInput?.aprovacaoViabilidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7rTQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7rjQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoViabilidade">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_APpWQy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_APpWRC-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_APpWRS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_APpWRy-EEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_APpWRi-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_AkY3Ny-EEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_RW58UDQdEfCDrJ8UxzY4jg" name="AnalisarViabilidadeTecnicaForm" content="a0cff1d9-91eb-42ae-9ef0-0e34f3caca21" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_AkY3Ni-EEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_PoJUcDQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUcTQdEfCDrJ8UxzY4jg" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUcjQdEfCDrJ8UxzY4jg" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUczQdEfCDrJ8UxzY4jg" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUdDQdEfCDrJ8UxzY4jg" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUdTQdEfCDrJ8UxzY4jg" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUdjQdEfCDrJ8UxzY4jg" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUdzQdEfCDrJ8UxzY4jg" name="comentarioEngenharia" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUeDQdEfCDrJ8UxzY4jg" name="aprovacaoEngenharia" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUeTQdEfCDrJ8UxzY4jg" name="ordemServicoRequisitos" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUejQdEfCDrJ8UxzY4jg" name="requisitos" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUezQdEfCDrJ8UxzY4jg" name="analiseViabilidade" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUfDQdEfCDrJ8UxzY4jg" name="aprovacaoViabilidade" type="BOOLEAN" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_PoJUfTQdEfCDrJ8UxzY4jg" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_PoJUfjQdEfCDrJ8UxzY4jg" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_PoJUfzQdEfCDrJ8UxzY4jg" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_AkY3OS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_PEd1cC-EEfC1UoIdMei-qg" name="Viável" outgoing="_YUkH0C-EEfC1UoIdMei-qg _cvKq4i-EEfC1UoIdMei-qg" incoming="_OFHRQC-EEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OFE1AC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OFEN8C-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OFE1AS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_gRC2MC-EEfC1UoIdMei-qg" name="Fim - Melhoria Inviável" incoming="_cvKq4i-EEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gRDdQS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gRDdQC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gRDdQi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_lt7VoC-EEfC1UoIdMei-qg" name="Formalizar Documentação" outgoing="_wZaA4C-EEfC1UoIdMei-qg" incoming="_YUkH0C-EEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YUiSoS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YUiSoC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YUiSoi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_r_HxGjQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_r_HxGzQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_r_HxHDQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_r_HxHTQdEfCDrJ8UxzY4jg" name="melhoriaInput.linkDocumentoFormalizado" content="melhoriaInput?.linkDocumentoFormalizado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_r_HxHjQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_r_HxHzQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setLinkDocumentoFormalizado">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YUiSoy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YUi5sC-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YUi5sS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YUi5sy-EEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YUi5si-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_lt78uS-EEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_vA3DwDQdEfCDrJ8UxzY4jg" name="EnviarDocumentacaoFormalizadaForm" content="672c8b82-6b30-4d59-a5a6-254318527157" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_lt78uC-EEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_r_HxEDQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_r_HxEjQdEfCDrJ8UxzY4jg" name="linkDocumentoFormalizado" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_r_HxEzQdEfCDrJ8UxzY4jg" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_lt78uy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_5Qad0C-EEfC1UoIdMei-qg" name="3 Meses" outgoing="_EvizkS-FEfC1UoIdMei-qg" incoming="_5QhLgC-EEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5QcTAS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5QcTAC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5QcTAi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_63ZCsC-EEfC1UoIdMei-qg" name="00:03:00" content="180000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_H-JdkC-FEfC1UoIdMei-qg" name="Avaliar Ganhos Reais" outgoing="_MH46IS-FEfC1UoIdMei-qg" incoming="_EvizkS-FEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EvhlcS-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EvhlcC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Evhlci-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5ljQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5lzQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5mDQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5mTQfEfCDrJ8UxzY4jg" name="melhoriaInput.linkDocumentoFormalizado" content="melhoriaInput?.linkDocumentoFormalizado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5mjQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5mzQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setLinkDocumentoFormalizado">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5nDQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5nTQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5njQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5nzQfEfCDrJ8UxzY4jg" name="melhoriaInput.ordemServicoExecucao" content="melhoriaInput?.ordemServicoExecucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5oDQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5oTQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOrdemServicoExecucao">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5ojQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5ozQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5pDQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5pTQfEfCDrJ8UxzY4jg" name="melhoriaInput.analiseGanhos" content="melhoriaInput?.analiseGanhos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5pjQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5pzQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAnaliseGanhos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5qDQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5qTQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5qjQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5qzQfEfCDrJ8UxzY4jg" name="melhoriaInput.ganhosAnuaisComMelhoria" content="melhoriaInput?.ganhosAnuaisComMelhoria" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Double">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5rDQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5rTQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setGanhosAnuaisComMelhoria">
              <inputTypes>java.lang.Double</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5rjQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5rzQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5sDQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5sTQfEfCDrJ8UxzY4jg" name="melhoriaInput.ganhosAprovados" content="melhoriaInput?.ganhosAprovados" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5sjQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5szQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setGanhosAprovados">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Evhlcy-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EvhldC-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EvhldS-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Evhldy-FEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Evhldi-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_H-Krsy-FEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_Hme5MDQfEfCDrJ8UxzY4jg" name="AnaliseGanhosForm" content="c9218921-34b9-41ee-a8d1-18108d855324" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_H-Krsi-FEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_G0L5kDQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5kTQfEfCDrJ8UxzY4jg" name="linkDocumentoFormalizado" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5kjQfEfCDrJ8UxzY4jg" name="ordemServicoExecucao" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5kzQfEfCDrJ8UxzY4jg" name="analiseGanhos" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5lDQfEfCDrJ8UxzY4jg" name="ganhosAnuaisComMelhoria" type="DECIMAL" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5lTQfEfCDrJ8UxzY4jg" name="ganhosAprovados" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_H-KrtS-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_YwpxcC-FEfC1UoIdMei-qg" name="Fim - Ganho Não Comprovado" incoming="_VLbXMC-FEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ywq_kC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YwqYgC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ywq_kS-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_RV2lEC-LEfC1UoIdMei-qg" name="Ganhos Comprovados?" outgoing="_Pr7ooS-FEfC1UoIdMei-qg _VLbXMC-FEfC1UoIdMei-qg" incoming="_MH46IS-FEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MH3sAS-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MH3sAC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MH3sAi-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_fOYRkC9_EfCqJOVmptBMqg" name="Manutenção" actor="_VEfvIC-NEfC1UoIdMei-qg">
        <elements xmi:type="process:Task" xmi:id="_8sfYkC-DEfC1UoIdMei-qg" name="Avaliar Requisitos" outgoing="_APqkYC-EEfC1UoIdMei-qg" incoming="_8M-LAC-DEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8M884S-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8M884C-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8M884i-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8M884y-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8M885C-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8M885S-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8M885y-DEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8M885i-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_8sf_qS-DEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_qZlolTQbEfCDrJ8UxzY4jg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_8sf_qC-DEfC1UoIdMei-qg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_8sgmsC-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_HiElkC-FEfC1UoIdMei-qg" name="Implantar Melhoria" outgoing="_5QhLgC-EEfC1UoIdMei-qg" incoming="_y2P2wC-EEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_y2K-QS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_y2K-QC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_y2LlUC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_y2LlUS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_y2LlUi-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_y2LlUy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_y2MMYS-EEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_y2MMYC-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HiFzti-FEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_qZloljQbEfCDrJ8UxzY4jg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HiFztS-FEfC1UoIdMei-qg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HiFzuC-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_1377kC-DEfC1UoIdMei-qg" name="PCM" actor="_WqMhoC-NEfC1UoIdMei-qg">
        <elements xmi:type="process:Task" xmi:id="_6ztSAC-DEfC1UoIdMei-qg" name="Gerar Ordem de Serviço - Requisitos" outgoing="_8M-LAC-DEfC1UoIdMei-qg" incoming="_4XxbEC-DEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4XwM8S-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4XwM8C-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4XwM8i-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_2gMYkDQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2gMYkTQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2gMYkjQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2gMYkzQcEfCDrJ8UxzY4jg" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2gMYlDQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2gMYlTQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_2gMYljQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2gMYlzQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2gMYmDQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2gMYmTQcEfCDrJ8UxzY4jg" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2gMYmjQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2gMYmzQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_2gMYnDQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2gMYnTQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2gMYnjQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2gMYnzQcEfCDrJ8UxzY4jg" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2gMYoDQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2gMYoTQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_2gMYojQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2gMYozQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2gMYpDQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2gMYpTQcEfCDrJ8UxzY4jg" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2gMYpjQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2gMYpzQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_2gMYqDQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2gMYqTQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2gMYqjQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2gMYqzQcEfCDrJ8UxzY4jg" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2gMYrDQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2gMYrTQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_2gMYrjQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2gMYrzQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2gMYsDQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2gMYsTQcEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2gMYsjQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2gMYszQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_2gMYtDQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2gMYtTQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2gMYtjQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2gMYtzQcEfCDrJ8UxzY4jg" name="melhoriaInput.ordemServicoRequisitos" content="melhoriaInput?.ordemServicoRequisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2gMYuDQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2gMYuTQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOrdemServicoRequisitos">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_2gMYujQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2gMYuzQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2gMYvDQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2gMYvTQcEfCDrJ8UxzY4jg" name="melhoriaInput.requisitos" content="melhoriaInput?.requisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2gMYvjQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2gMYvzQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setRequisitos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4XwM8y-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4XwM9C-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4XwM9S-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4Xw0AC-DEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4XwM9i-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_6zt5GS-DEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_68dIgDQcEfCDrJ8UxzY4jg" name="GerarOrdemServicoForm" content="93a509fd-835a-4bb1-9b3a-99a5b2787436" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_6zt5GC-DEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_2gLxgDQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_2gLxgTQcEfCDrJ8UxzY4jg" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_2gLxgjQcEfCDrJ8UxzY4jg" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_2gLxgzQcEfCDrJ8UxzY4jg" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_2gLxhDQcEfCDrJ8UxzY4jg" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_2gLxhTQcEfCDrJ8UxzY4jg" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_2gLxhjQcEfCDrJ8UxzY4jg" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_2gLxhzQcEfCDrJ8UxzY4jg" name="ordemServicoRequisitos" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_2gLxiDQcEfCDrJ8UxzY4jg" name="requisitos" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_2gLxiTQcEfCDrJ8UxzY4jg" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_2gLxijQcEfCDrJ8UxzY4jg" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_2gLxizQcEfCDrJ8UxzY4jg" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_6zt5Gy-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_8PPwoDQdEfCDrJ8UxzY4jg" name="Gerar Ordem de Serviço - Execucao" outgoing="_y2P2wC-EEfC1UoIdMei-qg" incoming="_wZaA4C-EEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wZYLsS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wZYLsC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wZYLsi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wZYLsy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wZYLtC-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wZYLtS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wZYLty-EEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wZYLti-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_8PTbCTQdEfCDrJ8UxzY4jg">
            <targetForm xmi:type="expression:Expression" xmi:id="_8PTbCjQdEfCDrJ8UxzY4jg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_8PTbCDQdEfCDrJ8UxzY4jg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_8PTbCzQdEfCDrJ8UxzY4jg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Ytpj8C-JEfC1UoIdMei-qg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Mir7kC-MEfC1UoIdMei-qg" name="initMelhoria()" content="def melhoriaVar = new com.company.model.Melhoria()&#xD;&#xA;melhoriaVar.oQueFazer = melhoriaInput?.oQueFazer&#xD;&#xA;melhoriaVar.comoFazer = melhoriaInput?.comoFazer&#xD;&#xA;melhoriaVar.ondeFazer = melhoriaInput?.ondeFazer&#xD;&#xA;return melhoriaVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Melhoria">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_Mir7kS-MEfC1UoIdMei-qg" name="melhoriaInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_48bZmS9-EfCqJOVmptBMqg">
        <targetForm xmi:type="expression:Expression" xmi:id="__dHVcDQKEfC8CYkRjdP_Iw" name="RequisicaoMelhoriaForm" content="74c45661-2694-4b96-af30-fb4c71806aa1" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_48bZmy9-EfCqJOVmptBMqg">
        <targetForm xmi:type="expression:Expression" xmi:id="_48bZnC9-EfCqJOVmptBMqg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EcSLQC-DEfC1UoIdMei-qg" target="_E81TkC-DEfC1UoIdMei-qg" source="_4zYp8C-MEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EcSyUC-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_EcSyUS-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VKRLgC-DEfC1UoIdMei-qg" target="_Wv7hwC-DEfC1UoIdMei-qg" source="_E81TkC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VKRLgS-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_VKRLgi-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XYuAEC-DEfC1UoIdMei-qg" name="Mais Informações" target="_4zYp8C-MEfC1UoIdMei-qg" source="_Wv7hwC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XYunIC-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_XYunIS-DEfC1UoIdMei-qg" name="solicitarInformacoesMelhoria()" content="melhoria.aprovacaoGestor == &quot;Solicitar Informações&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_98W2QC-JEfC1UoIdMei-qg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZBq64C-DEfC1UoIdMei-qg" name="Reprovada" target="_b0KQoC-DEfC1UoIdMei-qg" source="_Wv7hwC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZBq64S-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZBq64i-DEfC1UoIdMei-qg" name="AprovarMelhoriaGestor()" content="melhoria.aprovacaoGestor == &quot;Reprovada&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Foh3wC-KEfC1UoIdMei-qg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nSswgS-DEfC1UoIdMei-qg" name="Aprovada" target="_nSptMC-DEfC1UoIdMei-qg" source="_Wv7hwC-DEfC1UoIdMei-qg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nSswgi-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_nSswgy-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pst74C-DEfC1UoIdMei-qg" target="_svB2UC-DEfC1UoIdMei-qg" source="_nSptMC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pst74S-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_pst74i-DEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rOnMcC-DEfC1UoIdMei-qg" name="Reprovada" target="_vKE8cC-DEfC1UoIdMei-qg" source="_svB2UC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rOnMcS-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_rOnMci-DEfC1UoIdMei-qg" name="newScript()" content="melhoria.aprovacaoEngenharia == False" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_-g4DIC-KEfC1UoIdMei-qg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4XxbEC-DEfC1UoIdMei-qg" name="Aprovada Engenharia" target="_6ztSAC-DEfC1UoIdMei-qg" source="_svB2UC-DEfC1UoIdMei-qg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4XxbES-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4XyCIC-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8M-LAC-DEfC1UoIdMei-qg" target="_8sfYkC-DEfC1UoIdMei-qg" source="_6ztSAC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8M-LAS-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_8M-LAi-DEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_APqkYC-EEfC1UoIdMei-qg" target="_AkXpEC-EEfC1UoIdMei-qg" source="_8sfYkC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_APqkYS-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_APrLcC-EEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OFHRQC-EEfC1UoIdMei-qg" target="_PEd1cC-EEfC1UoIdMei-qg" source="_AkXpEC-EEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OFHRQS-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OFH4UC-EEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YUkH0C-EEfC1UoIdMei-qg" name="Viável" target="_lt7VoC-EEfC1UoIdMei-qg" source="_PEd1cC-EEfC1UoIdMei-qg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YUku4C-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_YUku4S-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cvKq4i-EEfC1UoIdMei-qg" name="Inviável" target="_gRC2MC-EEfC1UoIdMei-qg" source="_PEd1cC-EEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cvLR8C-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_cvLR8S-EEfC1UoIdMei-qg" name="newScript()" content="melhoria.aprovacaoViabilidade == False" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MzRxwC-LEfC1UoIdMei-qg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wZaA4C-EEfC1UoIdMei-qg" target="_8PPwoDQdEfCDrJ8UxzY4jg" source="_lt7VoC-EEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wZaA4S-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_wZan8C-EEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_y2P2wC-EEfC1UoIdMei-qg" target="_HiElkC-FEfC1UoIdMei-qg" source="_8PPwoDQdEfCDrJ8UxzY4jg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_y2Qd0C-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_y2Qd0S-EEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5QhLgC-EEfC1UoIdMei-qg" target="_5Qad0C-EEfC1UoIdMei-qg" source="_HiElkC-FEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5QhykC-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_5QhykS-EEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EvizkS-FEfC1UoIdMei-qg" target="_H-JdkC-FEfC1UoIdMei-qg" source="_5Qad0C-EEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EvjaoC-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_EvjaoS-FEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MH46IS-FEfC1UoIdMei-qg" target="_RV2lEC-LEfC1UoIdMei-qg" source="_H-JdkC-FEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MH5hMC-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_MH5hMS-FEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pr7ooS-FEfC1UoIdMei-qg" name="Sim" target="_P_uHUC-FEfC1UoIdMei-qg" source="_RV2lEC-LEfC1UoIdMei-qg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pr8PsC-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pr8PsS-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sb8SIC-FEfC1UoIdMei-qg" target="_Sb514C-FEfC1UoIdMei-qg" source="_P_uHUC-FEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sb8SIS-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sb85MC-FEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VLbXMC-FEfC1UoIdMei-qg" name="Não" target="_YwpxcC-FEfC1UoIdMei-qg" source="_RV2lEC-LEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VLbXMS-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_VLbXMi-FEfC1UoIdMei-qg" name="newScript()" content="melhoria.ganhosAprovados == False" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UUncQC-LEfC1UoIdMei-qg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ar0X4zQKEfC8CYkRjdP_Iw" target="_15RnsDQKEfC8CYkRjdP_Iw" source="_48aygy9-EfCqJOVmptBMqg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ar0-8DQKEfC8CYkRjdP_Iw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ar0-8TQKEfC8CYkRjdP_Iw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lrOEsDQKEfC8CYkRjdP_Iw" target="_E81TkC-DEfC1UoIdMei-qg" source="_15RnsDQKEfC8CYkRjdP_Iw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lrWnkDQKEfC8CYkRjdP_Iw"/>
        <condition xmi:type="expression:Expression" xmi:id="_lrWnkTQKEfC8CYkRjdP_Iw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_48bZoC9-EfCqJOVmptBMqg" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_SeTI8C-NEfC1UoIdMei-qg" name="Gestor_actor"/>
      <actors xmi:type="process:Actor" xmi:id="_TsjEwC-NEfC1UoIdMei-qg" name="Engenharia_actor"/>
      <actors xmi:type="process:Actor" xmi:id="_VEfvIC-NEfC1UoIdMei-qg" name="Manutencao_actor"/>
      <actors xmi:type="process:Actor" xmi:id="_WqMhoC-NEfC1UoIdMei-qg" name="PCM_actor"/>
      <contract xmi:type="process:Contract" xmi:id="_48bZoS9-EfCqJOVmptBMqg">
        <inputs xmi:type="process:ContractInput" xmi:id="_MirUgC-MEfC1UoIdMei-qg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria">
          <inputs xmi:type="process:ContractInput" xmi:id="_MirUgS-MEfC1UoIdMei-qg" name="oQueFazer"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_MirUgi-MEfC1UoIdMei-qg" name="comoFazer"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_MirUgy-MEfC1UoIdMei-qg" name="ondeFazer"/>
        </inputs>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_MirUhC-MEfC1UoIdMei-qg" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
          <inputNames>melhoriaInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_MirUhS-MEfC1UoIdMei-qg" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
          <inputNames>melhoriaInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_MirUhi-MEfC1UoIdMei-qg" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
          <inputNames>melhoriaInput</inputNames>
        </constraints>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZoi9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZoy9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZpC9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZpS9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZpi9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZpy9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZqC9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZqS9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZqi9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZqy9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZrC9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZrS9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZri9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZry9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZsC9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_48bZsS9-EfCqJOVmptBMqg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_48bZsi9-EfCqJOVmptBMqg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_48bZsy9-EfCqJOVmptBMqg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_48bZtC9-EfCqJOVmptBMqg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_48bZtS9-EfCqJOVmptBMqg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_48bZti9-EfCqJOVmptBMqg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_48bZty9-EfCqJOVmptBMqg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_48bZuC9-EfCqJOVmptBMqg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_48bZuS9-EfCqJOVmptBMqg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_48bZui9-EfCqJOVmptBMqg" type="Process" element="_48aygC9-EfCqJOVmptBMqg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_48bZuy9-EfCqJOVmptBMqg" type="2007" element="_48aygS9-EfCqJOVmptBMqg">
      <children xmi:type="notation:DecorationNode" xmi:id="_48bZvC9-EfCqJOVmptBMqg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_48bZvS9-EfCqJOVmptBMqg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_48bZvi9-EfCqJOVmptBMqg" type="3007" element="_48aygi9-EfCqJOVmptBMqg">
          <children xmi:type="notation:DecorationNode" xmi:id="_48bZvy9-EfCqJOVmptBMqg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_48bZwC9-EfCqJOVmptBMqg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_48bZxC9-EfCqJOVmptBMqg" type="3002" element="_48aygy9-EfCqJOVmptBMqg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_48bZxS9-EfCqJOVmptBMqg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_48bZxi9-EfCqJOVmptBMqg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_48bZxy9-EfCqJOVmptBMqg" x="42" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4zbtQC-MEfC1UoIdMei-qg" type="3005" element="_4zYp8C-MEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4zbtQi-MEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4zbtQS-MEfC1UoIdMei-qg" x="280" y="111" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_15SOzDQKEfC8CYkRjdP_Iw" type="3005" element="_15RnsDQKEfC8CYkRjdP_Iw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_15SOzjQKEfC8CYkRjdP_Iw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_15SOzTQKEfC8CYkRjdP_Iw" x="117" y="54" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_48bZyC9-EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_48bZyS9-EfCqJOVmptBMqg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_48bZyi9-EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_48bZyy9-EfCqJOVmptBMqg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_48bZzC9-EfCqJOVmptBMqg"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_eMbsYC9_EfCqJOVmptBMqg" type="3007" element="_eJCaIC9_EfCqJOVmptBMqg">
          <children xmi:type="notation:DecorationNode" xmi:id="_eMdhkC9_EfCqJOVmptBMqg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eMeIoC9_EfCqJOVmptBMqg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_E8498y-DEfC1UoIdMei-qg" type="3005" element="_E81TkC-DEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E86MEC-DEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E8499C-DEfC1UoIdMei-qg" x="99" y="104" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Wv9W8C-DEfC1UoIdMei-qg" type="3008" element="_Wv7hwC-DEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Wv9-AC-DEfC1UoIdMei-qg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Wv9-AS-DEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Wv9W8S-DEfC1UoIdMei-qg" x="308" y="102" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_b0MF0C-DEfC1UoIdMei-qg" type="3062" element="_b0KQoC-DEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_b0MF0i-DEfC1UoIdMei-qg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_b0MF0y-DEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b0MF0S-DEfC1UoIdMei-qg" x="498" y="115"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_P_vVcC-FEfC1UoIdMei-qg" type="3005" element="_P_uHUC-FEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_P_vVci-FEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P_vVcS-FEfC1UoIdMei-qg" x="1729" y="101" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Sb7EAC-FEfC1UoIdMei-qg" type="3003" element="_Sb514C-FEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Sb7rEC-FEfC1UoIdMei-qg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Sb7rES-FEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Sb7EAS-FEfC1UoIdMei-qg" x="1909" y="119"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eMbsYS9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eMcTcC9_EfCqJOVmptBMqg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eMcTcS9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eMeIoS9_EfCqJOVmptBMqg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eMcTci9_EfCqJOVmptBMqg" x="233" y="185"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_eiIPkC9_EfCqJOVmptBMqg" type="3007" element="_eiGaYC9_EfCqJOVmptBMqg">
          <children xmi:type="notation:DecorationNode" xmi:id="_eiJdsC9_EfCqJOVmptBMqg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eiJdsS9_EfCqJOVmptBMqg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_nSriYC-DEfC1UoIdMei-qg" type="3027" element="_nSptMC-DEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nSswgC-DEfC1UoIdMei-qg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nSriYS-DEfC1UoIdMei-qg" x="293" y="113" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_svCdYi-DEfC1UoIdMei-qg" type="3008" element="_svB2UC-DEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_svDEcS-DEfC1UoIdMei-qg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_svDEci-DEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_svDEcC-DEfC1UoIdMei-qg" x="472" y="121" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vKJ08C-DEfC1UoIdMei-qg" type="3062" element="_vKE8cC-DEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vKLDEC-DEfC1UoIdMei-qg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vKLDES-DEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vKJ08S-DEfC1UoIdMei-qg" x="669" y="128" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AkZeQC-EEfC1UoIdMei-qg" type="3005" element="_AkXpEC-EEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_AkaFUC-EEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AkZeQS-EEfC1UoIdMei-qg" x="858" y="117" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PEfDkC-EEfC1UoIdMei-qg" type="3008" element="_PEd1cC-EEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PEfDki-EEfC1UoIdMei-qg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PEfDky-EEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PEfDkS-EEfC1UoIdMei-qg" x="1065" y="128" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gREEUC-EEfC1UoIdMei-qg" type="3062" element="_gRC2MC-EEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gREEUi-EEfC1UoIdMei-qg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gRFScC-EEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gREEUS-EEfC1UoIdMei-qg" x="1078" y="40"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lt78vC-EEfC1UoIdMei-qg" type="3005" element="_lt7VoC-EEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lt8jwC-EEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lt78vS-EEfC1UoIdMei-qg" x="1165" y="128" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5QeIMC-EEfC1UoIdMei-qg" type="3017" element="_5Qad0C-EEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5QfWUC-EEfC1UoIdMei-qg" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5QfWUS-EEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5QeIMS-EEfC1UoIdMei-qg" x="1409" y="140"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_H-Krti-FEfC1UoIdMei-qg" type="3005" element="_H-JdkC-FEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_H-KruC-FEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_H-Krty-FEfC1UoIdMei-qg" x="1555" y="134" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ywq_ki-FEfC1UoIdMei-qg" type="3062" element="_YwpxcC-FEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_YwrmoC-FEfC1UoIdMei-qg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_YwrmoS-FEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ywq_ky-FEfC1UoIdMei-qg" x="1909" y="143"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RV3zMC-LEfC1UoIdMei-qg" type="3008" element="_RV2lEC-LEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_RV4aQC-LEfC1UoIdMei-qg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_RV4aQS-LEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RV3zMS-LEfC1UoIdMei-qg" x="1756" y="144" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eiIPkS9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eiIPki9_EfCqJOVmptBMqg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eiIPky9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eiJdsi9_EfCqJOVmptBMqg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eiIPlC9_EfCqJOVmptBMqg" x="319" y="418"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_fOaGwC9_EfCqJOVmptBMqg" type="3007" element="_fOYRkC9_EfCqJOVmptBMqg">
          <children xmi:type="notation:DecorationNode" xmi:id="_fObU4C9_EfCqJOVmptBMqg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_fObU4S9_EfCqJOVmptBMqg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_8sgmsS-DEfC1UoIdMei-qg" type="3005" element="_8sfYkC-DEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8shNwC-DEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8sgmsi-DEfC1UoIdMei-qg" x="707" y="102" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HiFzuS-FEfC1UoIdMei-qg" type="3005" element="_HiElkC-FEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HiGawC-FEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HiFzui-FEfC1UoIdMei-qg" x="1372" y="102" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_fOaGwS9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_fOaGwi9_EfCqJOVmptBMqg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_fOaGwy9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_fObU4i9_EfCqJOVmptBMqg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fOaGxC9_EfCqJOVmptBMqg" x="203" y="533"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_13-X0C-DEfC1UoIdMei-qg" type="3007" element="_1377kC-DEfC1UoIdMei-qg">
          <children xmi:type="notation:DecorationNode" xmi:id="_13--4C-DEfC1UoIdMei-qg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_13--4S-DEfC1UoIdMei-qg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_6zvHMC-DEfC1UoIdMei-qg" type="3005" element="_6ztSAC-DEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6zvuQC-DEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6zvHMS-DEfC1UoIdMei-qg" x="444" y="100" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8PXscDQdEfCDrJ8UxzY4jg" type="3005" element="_8PPwoDQdEfCDrJ8UxzY4jg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8PYTgDQdEfCDrJ8UxzY4jg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8PXscTQdEfCDrJ8UxzY4jg" x="1166" y="105" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_13-X0S-DEfC1UoIdMei-qg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_13-X0i-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_13-X0y-DEfC1UoIdMei-qg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_13--4i-DEfC1UoIdMei-qg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_13-X1C-DEfC1UoIdMei-qg" x="48" y="1000" width="1297" height="250"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_48bZzS9-EfCqJOVmptBMqg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_48bZzi9-EfCqJOVmptBMqg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_48bZzy9-EfCqJOVmptBMqg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_48bZ0C9-EfCqJOVmptBMqg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_48bZ0S9-EfCqJOVmptBMqg" width="2070" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_48bZ0i9-EfCqJOVmptBMqg"/>
    <edges xmi:type="notation:Connector" xmi:id="_EcTZYC-DEfC1UoIdMei-qg" type="4001" element="_EcSLQC-DEfC1UoIdMei-qg" source="_4zbtQC-MEfC1UoIdMei-qg" target="_E8498y-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EcUAcC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EcUAcS-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EcTZYS-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EcTZYi-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1n4XQC-MEfC1UoIdMei-qg" id="(0.775,0.35)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VKRykC-DEfC1UoIdMei-qg" type="4001" element="_VKRLgC-DEfC1UoIdMei-qg" source="_E8498y-DEfC1UoIdMei-qg" target="_Wv9W8C-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VKTAsC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VKTAsS-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VKRykS-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VKRyki-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XYv1QC-DEfC1UoIdMei-qg" type="4001" element="_XYuAEC-DEfC1UoIdMei-qg" source="_Wv9W8C-DEfC1UoIdMei-qg" target="_4zbtQC-MEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XYwcUC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XYwcUS-DEfC1UoIdMei-qg" x="4" y="78"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XYv1QS-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XYv1Qi-DEfC1UoIdMei-qg" points="[-14, -21, -7, 163]$[-14, -132, -7, 52]$[-21, -132, -14, 52]$[-21, -177, -14, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XY0twC-DEfC1UoIdMei-qg" id="(0.4186046511627907,0.09302325581395349)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zRaPIC-MEfC1UoIdMei-qg" id="(0.64,0.86)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZBrh8C-DEfC1UoIdMei-qg" type="4001" element="_ZBq64C-DEfC1UoIdMei-qg" source="_Wv9W8C-DEfC1UoIdMei-qg" target="_b0MF0C-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZBrh8y-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZBrh9C-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZBrh8S-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZBrh8i-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Cp2YwC-NEfC1UoIdMei-qg" id="(0.23333333333333334,0.36666666666666664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nSt-oC-DEfC1UoIdMei-qg" type="4001" element="_nSswgS-DEfC1UoIdMei-qg" source="_Wv9W8C-DEfC1UoIdMei-qg" target="_nSriYC-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nSulsC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nSulsS-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nSt-oS-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nSt-oi-DEfC1UoIdMei-qg" points="[0, 22, -24, -248]$[0, 240, -24, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pst74y-DEfC1UoIdMei-qg" type="4001" element="_pst74C-DEfC1UoIdMei-qg" source="_nSriYC-DEfC1UoIdMei-qg" target="_svCdYi-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_psui8C-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_psui8S-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pst75C-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pst75S-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rOnzgC-DEfC1UoIdMei-qg" type="4001" element="_rOnMcC-DEfC1UoIdMei-qg" source="_svCdYi-DEfC1UoIdMei-qg" target="_vKJ08C-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rOnzgy-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rOnzhC-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rOnzgS-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rOnzgi-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4XyCIS-DEfC1UoIdMei-qg" type="4001" element="_4XxbEC-DEfC1UoIdMei-qg" source="_svCdYi-DEfC1UoIdMei-qg" target="_6zvHMC-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4XyCJC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4XypMC-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4XyCIi-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4XyCIy-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8M-LAy-DEfC1UoIdMei-qg" type="4001" element="_8M-LAC-DEfC1UoIdMei-qg" source="_6zvHMC-DEfC1UoIdMei-qg" target="_8sgmsS-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8M-yEC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8M-yES-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8M-LBC-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8M-LBS-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_APrLcS-EEfC1UoIdMei-qg" type="4001" element="_APqkYC-EEfC1UoIdMei-qg" source="_8sgmsS-DEfC1UoIdMei-qg" target="_AkZeQC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_APrLdC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_APrLdS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_APrLci-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_APrLcy-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OFH4US-EEfC1UoIdMei-qg" type="4001" element="_OFHRQC-EEfC1UoIdMei-qg" source="_AkZeQC-EEfC1UoIdMei-qg" target="_PEfDkC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OFJGcC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OFJGcS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OFH4Ui-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OFH4Uy-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YUlV8C-EEfC1UoIdMei-qg" type="4001" element="_YUkH0C-EEfC1UoIdMei-qg" source="_PEfDkC-EEfC1UoIdMei-qg" target="_lt78vC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YUl9AC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YUl9AS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YUlV8S-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YUlV8i-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cvLR8i-EEfC1UoIdMei-qg" type="4001" element="_cvKq4i-EEfC1UoIdMei-qg" source="_PEfDkC-EEfC1UoIdMei-qg" target="_gREEUC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cvL5AC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cvL5AS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cvLR8y-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cvLR9C-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GQtKsC-NEfC1UoIdMei-qg" id="(0.2,0.7666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wZbPAC-EEfC1UoIdMei-qg" type="4001" element="_wZaA4C-EEfC1UoIdMei-qg" source="_lt78vC-EEfC1UoIdMei-qg" target="_8PXscDQdEfCDrJ8UxzY4jg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wZbPAy-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wZbPBC-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wZbPAS-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wZbPAi-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_y2RE4C-EEfC1UoIdMei-qg" type="4001" element="_y2P2wC-EEfC1UoIdMei-qg" source="_8PXscDQdEfCDrJ8UxzY4jg" target="_HiFzuS-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_y2Rr8C-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_y2STAC-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_y2RE4S-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y2RE4i-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5QiZoC-EEfC1UoIdMei-qg" type="4001" element="_5QhLgC-EEfC1UoIdMei-qg" source="_HiFzuS-FEfC1UoIdMei-qg" target="_5QeIMC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5QjnwC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5QjnwS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5QiZoS-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5QiZoi-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Evjaoi-FEfC1UoIdMei-qg" type="4001" element="_EvizkS-FEfC1UoIdMei-qg" source="_5QeIMC-EEfC1UoIdMei-qg" target="_H-Krti-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EvjapS-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Evjapi-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Evjaoy-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EvjapC-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MH5hMi-FEfC1UoIdMei-qg" type="4001" element="_MH46IS-FEfC1UoIdMei-qg" source="_H-Krti-FEfC1UoIdMei-qg" target="_RV3zMC-LEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MH6IQC-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MH6IQS-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MH5hMy-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MH5hNC-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pr8Psi-FEfC1UoIdMei-qg" type="4001" element="_Pr7ooS-FEfC1UoIdMei-qg" source="_RV3zMC-LEfC1UoIdMei-qg" target="_P_vVcC-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pr82wC-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pr82wS-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pr8Psy-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pr8PtC-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sb9gQC-FEfC1UoIdMei-qg" type="4001" element="_Sb8SIC-FEfC1UoIdMei-qg" source="_P_vVcC-FEfC1UoIdMei-qg" target="_Sb7EAC-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sb-uYC-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sb-uYS-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sb9gQS-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sb9gQi-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VLb-QC-FEfC1UoIdMei-qg" type="4001" element="_VLbXMC-FEfC1UoIdMei-qg" source="_RV3zMC-LEfC1UoIdMei-qg" target="_Ywq_ki-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VLb-Qy-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VLb-RC-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VLb-QS-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VLb-Qi-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ar0-8jQKEfC8CYkRjdP_Iw" type="4001" element="_ar0X4zQKEfC8CYkRjdP_Iw" source="_48bZxC9-EfCqJOVmptBMqg" target="_15SOzDQKEfC8CYkRjdP_Iw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ar0-9TQKEfC8CYkRjdP_Iw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ar0-9jQKEfC8CYkRjdP_Iw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ar0-8zQKEfC8CYkRjdP_Iw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ar0-9DQKEfC8CYkRjdP_Iw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lrXOoDQKEfC8CYkRjdP_Iw" type="4001" element="_lrOEsDQKEfC8CYkRjdP_Iw" source="_15SOzDQKEfC8CYkRjdP_Iw" target="_E8498y-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lrX1sDQKEfC8CYkRjdP_Iw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lrX1sTQKEfC8CYkRjdP_Iw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lrXOoTQKEfC8CYkRjdP_Iw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lrXOojQKEfC8CYkRjdP_Iw" points="[-16, 51, 140, -433]$[-155, 475, 1, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lrZD0DQKEfC8CYkRjdP_Iw" id="(0.47863247863247865,0.9655172413793104)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lrZD0TQKEfC8CYkRjdP_Iw" id="(0.6166666666666667,0.1)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
