<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_48aygC9-EfCqJOVmptBMqg" name="Processo" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_48aygS9-EfCqJOVmptBMqg" name="SugestaoMelhoria" displayName="Sugestão Melhoria">
      <elements xmi:type="process:Lane" xmi:id="_48aygi9-EfCqJOVmptBMqg" name="Colaborador" actor="_48bZoC9-EfCqJOVmptBMqg">
        <elements xmi:type="process:StartEvent" xmi:id="_48aygy9-EfCqJOVmptBMqg" name="Proposta de melhoria" outgoing="_afCm0DUgEfC2kOjxAoQ4kw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_48ayhC9-EfCqJOVmptBMqg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_48ayhS9-EfCqJOVmptBMqg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_48ayhi9-EfCqJOVmptBMqg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_-dUmkC-PEfC1UoIdMei-qg" name="Iniciador" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_-dUmkS-PEfC1UoIdMei-qg" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-dUmki-PEfC1UoIdMei-qg" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_-dUmky-PEfC1UoIdMei-qg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_eJCaIC9_EfCqJOVmptBMqg" name="Gestor" actor="_SeTI8C-NEfC1UoIdMei-qg">
        <elements xmi:type="process:Task" xmi:id="_E81TkC-DEfC1UoIdMei-qg" name="Deliberar e Aprovar Melhoria" outgoing="_VKRLgC-DEfC1UoIdMei-qg" incoming="_afCm0DUgEfC2kOjxAoQ4kw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EcLdkS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EcLdkC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EcMEoC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfgzQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfhDQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfhTQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfhjQcEfCDrJ8UxzY4jg" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfhzQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfiDQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfiTQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfijQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfizQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfjDQcEfCDrJ8UxzY4jg" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfjTQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfjjQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfjzQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfkDQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfkTQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfkjQcEfCDrJ8UxzY4jg" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfkzQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhflDQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhflTQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfljQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhflzQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfmDQcEfCDrJ8UxzY4jg" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfmTQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfmjQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfmzQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfnDQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfnTQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfnjQcEfCDrJ8UxzY4jg" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfnzQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfoDQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_AXhfoTQcEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AXhfojQcEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AXhfozQcEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AXhfpDQcEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_AXhfpTQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AXhfpjQcEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EcMEoS-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EcMEoi-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EcMEoy-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EcMEpS-DEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EcMEpC-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_E8498C-DEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_alH00DQcEfCDrJ8UxzY4jg" name="AvaliacaoRequisicaoGestorForm" content="9261ac36-48f4-4d56-8a29-6e9a4c587978" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_E84W4S-DEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_AXg4cDQcEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4cTQcEfCDrJ8UxzY4jg" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4cjQcEfCDrJ8UxzY4jg" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4czQcEfCDrJ8UxzY4jg" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4dDQcEfCDrJ8UxzY4jg" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4dTQcEfCDrJ8UxzY4jg" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_AXg4djQcEfCDrJ8UxzY4jg" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_E8498i-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Wv7hwC-DEfC1UoIdMei-qg" name="Aprovada?" outgoing="_ZBq64C-DEfC1UoIdMei-qg _nSswgS-DEfC1UoIdMei-qg" incoming="_VKRLgC-DEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VKPWUS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VKPWUC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VKPWUi-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_b0KQoC-DEfC1UoIdMei-qg" name="Fim - Reprovada pelo Gestor" incoming="_ZBq64C-DEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_b0KQoi-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_b0KQoS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_b0KQoy-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_P_uHUC-FEfC1UoIdMei-qg" name="Comunica Colaborador" outgoing="_Sb8SIC-FEfC1UoIdMei-qg" incoming="_Pr7ooS-FEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pr5zcS-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pr5zcC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pr5zci-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pr5zcy-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pr5zdC-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Pr5zdS-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Pr6agS-FEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Pr6agC-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_P_uuaS-FEfC1UoIdMei-qg" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_IoMXYDacEfCpDtQ9qE9TEA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_P_uuaC-FEfC1UoIdMei-qg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_P_uuay-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Sb514C-FEfC1UoIdMei-qg" name="Melhoria Implantada" incoming="_Sb8SIC-FEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Sb6c8S-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Sb6c8C-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Sb6c8i-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_ZOVDkC-TEfC1UoIdMei-qg" name="Gestor" definitionId="bonita-actorfilter-initiator-manager" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_ZOVDkS-TEfC1UoIdMei-qg" definitionId="bonita-actorfilter-initiator-manager" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ZOVDki-TEfC1UoIdMei-qg" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_ZOVDky-TEfC1UoIdMei-qg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_eiGaYC9_EfCqJOVmptBMqg" name="Engenharia" actor="_TsjEwC-NEfC1UoIdMei-qg">
        <elements xmi:type="process:XORGateway" xmi:id="_svB2UC-DEfC1UoIdMei-qg" name="Aprovada Engenharia" outgoing="_rOnMcC-DEfC1UoIdMei-qg _4XxbEC-DEfC1UoIdMei-qg" incoming="_pst74C-DEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pssGsi-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pssGsS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pssGsy-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_vKE8cC-DEfC1UoIdMei-qg" name="Fim - Reprovada Engenharia" incoming="_rOnMcC-DEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ti0qwS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ti0qwC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ti1R0C-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AkXpEC-EEfC1UoIdMei-qg" name="Avaliar Viabilidade Técnica e Financeira" outgoing="_OFHRQC-EEfC1UoIdMei-qg" incoming="_APqkYC-EEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_APpWQS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_APpWQC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_APpWQi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUgDQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJUgTQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJUgjQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJUgzQdEfCDrJ8UxzY4jg" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJUhDQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJUhTQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUhjQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJUhzQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJUiDQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJUiTQdEfCDrJ8UxzY4jg" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJUijQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJUizQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUjDQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJUjTQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJUjjQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJUjzQdEfCDrJ8UxzY4jg" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJUkDQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJUkTQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUkjQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJUkzQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJUlDQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJUlTQdEfCDrJ8UxzY4jg" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJUljQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJUlzQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJUmDQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7gDQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7gTQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7gjQdEfCDrJ8UxzY4jg" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7gzQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7hDQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7hTQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7hjQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7hzQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7iDQdEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7iTQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7ijQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7izQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7jDQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7jTQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7jjQdEfCDrJ8UxzY4jg" name="melhoriaInput.comentarioEngenharia" content="melhoriaInput?.comentarioEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7jzQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7kDQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setComentarioEngenharia">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7kTQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7kjQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7kzQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7lDQdEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoEngenharia" content="melhoriaInput?.aprovacaoEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7lTQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7ljQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoEngenharia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7lzQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7mDQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7mTQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7mjQdEfCDrJ8UxzY4jg" name="melhoriaInput.ordemServicoRequisitos" content="melhoriaInput?.ordemServicoRequisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7mzQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7nDQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOrdemServicoRequisitos">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7nTQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7njQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7nzQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7oDQdEfCDrJ8UxzY4jg" name="melhoriaInput.requisitos" content="melhoriaInput?.requisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7oTQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7ojQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setRequisitos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7ozQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7pDQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7pTQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7pjQdEfCDrJ8UxzY4jg" name="melhoriaInput.analiseViabilidade" content="melhoriaInput?.analiseViabilidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7pzQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7qDQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAnaliseViabilidade">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PoJ7qTQdEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PoJ7qjQdEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PoJ7qzQdEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PoJ7rDQdEfCDrJ8UxzY4jg" name="melhoriaInput.aprovacaoViabilidade" content="melhoriaInput?.aprovacaoViabilidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PoJ7rTQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PoJ7rjQdEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAprovacaoViabilidade">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_APpWQy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_APpWRC-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_APpWRS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_APpWRy-EEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_APpWRi-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_AkY3Ny-EEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_RW58UDQdEfCDrJ8UxzY4jg" name="AnalisarViabilidadeTecnicaForm" content="a0cff1d9-91eb-42ae-9ef0-0e34f3caca21" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_AkY3Ni-EEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_PoJUcDQdEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUcTQdEfCDrJ8UxzY4jg" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUcjQdEfCDrJ8UxzY4jg" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUczQdEfCDrJ8UxzY4jg" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUdDQdEfCDrJ8UxzY4jg" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUdTQdEfCDrJ8UxzY4jg" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUdjQdEfCDrJ8UxzY4jg" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUdzQdEfCDrJ8UxzY4jg" name="comentarioEngenharia" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUeDQdEfCDrJ8UxzY4jg" name="aprovacaoEngenharia" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUeTQdEfCDrJ8UxzY4jg" name="ordemServicoRequisitos" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUejQdEfCDrJ8UxzY4jg" name="requisitos" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUezQdEfCDrJ8UxzY4jg" name="analiseViabilidade" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PoJUfDQdEfCDrJ8UxzY4jg" name="aprovacaoViabilidade" type="BOOLEAN" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_PoJUfTQdEfCDrJ8UxzY4jg" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_PoJUfjQdEfCDrJ8UxzY4jg" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_PoJUfzQdEfCDrJ8UxzY4jg" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_AkY3OS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_PEd1cC-EEfC1UoIdMei-qg" name="Viável" outgoing="_YUkH0C-EEfC1UoIdMei-qg _cvKq4i-EEfC1UoIdMei-qg" incoming="_OFHRQC-EEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OFE1AC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OFEN8C-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OFE1AS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_gRC2MC-EEfC1UoIdMei-qg" name="Fim - Melhoria Inviável" incoming="_cvKq4i-EEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gRDdQS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gRDdQC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gRDdQi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_lt7VoC-EEfC1UoIdMei-qg" name="Formalizar Documentação" outgoing="_wZaA4C-EEfC1UoIdMei-qg" incoming="_YUkH0C-EEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YUiSoS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YUiSoC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YUiSoi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_wn5pgTUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5pgjUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5pgzUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5phDUiEfC2kOjxAoQ4kw" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5phTUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5phjUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5phzUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5piDUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5piTUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pijUiEfC2kOjxAoQ4kw" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5pizUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5pjDUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5pjTUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5pjjUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5pjzUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pkDUiEfC2kOjxAoQ4kw" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5pkTUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5pkjUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5pkzUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5plDUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5plTUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pljUiEfC2kOjxAoQ4kw" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5plzUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5pmDUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5pmTUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5pmjUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5pmzUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pnDUiEfC2kOjxAoQ4kw" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5pnTUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5pnjUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5pnzUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5poDUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5poTUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pojUiEfC2kOjxAoQ4kw" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5pozUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5ppDUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5ppTUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5ppjUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5ppzUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pqDUiEfC2kOjxAoQ4kw" name="melhoriaInput.comentarioEngenharia" content="melhoriaInput?.comentarioEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5pqTUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5pqjUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setComentarioEngenharia">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5pqzUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5prDUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5prTUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5prjUiEfC2kOjxAoQ4kw" name="melhoriaInput.aprovacaoEngenharia" content="melhoriaInput?.aprovacaoEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5przUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5psDUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setAprovacaoEngenharia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5psTUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5psjUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5pszUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5ptDUiEfC2kOjxAoQ4kw" name="melhoriaInput.ordemServicoRequisitos" content="melhoriaInput?.ordemServicoRequisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5ptTUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5ptjUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setOrdemServicoRequisitos">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5ptzUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5puDUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5puTUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pujUiEfC2kOjxAoQ4kw" name="melhoriaInput.requisitos" content="melhoriaInput?.requisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5puzUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5pvDUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setRequisitos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5pvTUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5pvjUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5pvzUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pwDUiEfC2kOjxAoQ4kw" name="melhoriaInput.analiseViabilidade" content="melhoriaInput?.analiseViabilidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5pwTUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5pwjUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setAnaliseViabilidade">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5pwzUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5pxDUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5pxTUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pxjUiEfC2kOjxAoQ4kw" name="melhoriaInput.aprovacaoViabilidade" content="melhoriaInput?.aprovacaoViabilidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5pxzUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5pyDUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setAprovacaoViabilidade">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wn5pyTUiEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wn5pyjUiEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wn5pyzUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wn5pzDUiEfC2kOjxAoQ4kw" name="melhoriaInput.linkDocumentoFormalizado" content="melhoriaInput?.linkDocumentoFormalizado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wn5pzTUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wn5pzjUiEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setLinkDocumentoFormalizado">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YUiSoy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YUi5sC-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YUi5sS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YUi5sy-EEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YUi5si-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_lt78uS-EEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_0MOEwDUiEfC2kOjxAoQ4kw" name="FormalizarDocumentoForm" content="9f3938fa-3a8b-43f0-b008-d4daed47b2a5" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_lt78uC-EEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_wn5pcDUiEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pcTUiEfC2kOjxAoQ4kw" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pcjUiEfC2kOjxAoQ4kw" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pczUiEfC2kOjxAoQ4kw" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pdDUiEfC2kOjxAoQ4kw" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pdTUiEfC2kOjxAoQ4kw" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pdjUiEfC2kOjxAoQ4kw" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pdzUiEfC2kOjxAoQ4kw" name="comentarioEngenharia" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5peDUiEfC2kOjxAoQ4kw" name="aprovacaoEngenharia" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5peTUiEfC2kOjxAoQ4kw" name="ordemServicoRequisitos" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pejUiEfC2kOjxAoQ4kw" name="requisitos" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pezUiEfC2kOjxAoQ4kw" name="analiseViabilidade" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pfDUiEfC2kOjxAoQ4kw" name="aprovacaoViabilidade" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wn5pfTUiEfC2kOjxAoQ4kw" name="linkDocumentoFormalizado" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_wn5pfjUiEfC2kOjxAoQ4kw" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_wn5pfzUiEfC2kOjxAoQ4kw" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_wn5pgDUiEfC2kOjxAoQ4kw" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_lt78uy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_5Qad0C-EEfC1UoIdMei-qg" name="3 Meses" outgoing="_EvizkS-FEfC1UoIdMei-qg" incoming="_5QhLgC-EEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5QcTAS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5QcTAC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5QcTAi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_63ZCsC-EEfC1UoIdMei-qg" name="00:01:00" content="60000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_H-JdkC-FEfC1UoIdMei-qg" name="Avaliar Ganhos Reais" outgoing="_MH46IS-FEfC1UoIdMei-qg" incoming="_EvizkS-FEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EvhlcS-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EvhlcC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Evhlci-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5ljQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5lzQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5mDQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5mTQfEfCDrJ8UxzY4jg" name="melhoriaInput.linkDocumentoFormalizado" content="melhoriaInput?.linkDocumentoFormalizado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5mjQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5mzQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setLinkDocumentoFormalizado">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5nDQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5nTQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5njQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5nzQfEfCDrJ8UxzY4jg" name="melhoriaInput.ordemServicoExecucao" content="melhoriaInput?.ordemServicoExecucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5oDQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5oTQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setOrdemServicoExecucao">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5ojQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5ozQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5pDQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5pTQfEfCDrJ8UxzY4jg" name="melhoriaInput.analiseGanhos" content="melhoriaInput?.analiseGanhos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5pjQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5pzQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setAnaliseGanhos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5qDQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5qTQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5qjQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5qzQfEfCDrJ8UxzY4jg" name="melhoriaInput.ganhosAnuaisComMelhoria" content="melhoriaInput?.ganhosAnuaisComMelhoria" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Double">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5rDQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5rTQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setGanhosAnuaisComMelhoria">
              <inputTypes>java.lang.Double</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_G0L5rjQfEfCDrJ8UxzY4jg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_G0L5rzQfEfCDrJ8UxzY4jg" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0L5sDQfEfCDrJ8UxzY4jg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_G0L5sTQfEfCDrJ8UxzY4jg" name="melhoriaInput.ganhosAprovados" content="melhoriaInput?.ganhosAprovados" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_G0L5sjQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_G0L5szQfEfCDrJ8UxzY4jg" type="JAVA_METHOD" expression="setGanhosAprovados">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Evhlcy-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EvhldC-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EvhldS-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Evhldy-FEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Evhldi-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_H-Krsy-FEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_Hme5MDQfEfCDrJ8UxzY4jg" name="AnaliseGanhosForm" content="c9218921-34b9-41ee-a8d1-18108d855324" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_H-Krsi-FEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_G0L5kDQfEfCDrJ8UxzY4jg" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5kTQfEfCDrJ8UxzY4jg" name="linkDocumentoFormalizado" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5kjQfEfCDrJ8UxzY4jg" name="ordemServicoExecucao" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5kzQfEfCDrJ8UxzY4jg" name="analiseGanhos" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5lDQfEfCDrJ8UxzY4jg" name="ganhosAnuaisComMelhoria" type="DECIMAL" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_G0L5lTQfEfCDrJ8UxzY4jg" name="ganhosAprovados" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_H-KrtS-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_YwpxcC-FEfC1UoIdMei-qg" name="Fim - Ganho Não Comprovado" incoming="_VLbXMC-FEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ywq_kC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YwqYgC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ywq_kS-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_RV2lEC-LEfC1UoIdMei-qg" name="Ganhos Comprovados?" outgoing="_Pr7ooS-FEfC1UoIdMei-qg _VLbXMC-FEfC1UoIdMei-qg" incoming="_MH46IS-FEfC1UoIdMei-qg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MH3sAS-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MH3sAC-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MH3sAi-FEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_y7fHkDUgEfC2kOjxAoQ4kw" name="Deliberar Relevancia da melhoria" outgoing="_pst74C-DEfC1UoIdMei-qg" incoming="_nSswgS-DEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nSqUQS-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nSqUQC-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nSqUQi-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_3WxAHDUgEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3WxAHTUgEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3WxAHjUgEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3WxAHzUgEfC2kOjxAoQ4kw" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3WxAIDUgEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3WxAITUgEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3WxAIjUgEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3WxAIzUgEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3WxAJDUgEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3WxAJTUgEfC2kOjxAoQ4kw" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3WxAJjUgEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3WxAJzUgEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3WxAKDUgEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3WxAKTUgEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3WxAKjUgEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3WxAKzUgEfC2kOjxAoQ4kw" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3WxALDUgEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3WxALTUgEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3WxALjUgEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3WxALzUgEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3WxAMDUgEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3WxAMTUgEfC2kOjxAoQ4kw" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3WxAMjUgEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3WxAMzUgEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3WxANDUgEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3WxANTUgEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3WxANjUgEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3WxANzUgEfC2kOjxAoQ4kw" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3WxAODUgEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3WxAOTUgEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3WxAOjUgEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3WxAOzUgEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3WxAPDUgEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3WxAPTUgEfC2kOjxAoQ4kw" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3WxAPjUgEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3WxAPzUgEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3WxAQDUgEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3WxAQTUgEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3WxAQjUgEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3WxAQzUgEfC2kOjxAoQ4kw" name="melhoriaInput.comentarioEngenharia" content="melhoriaInput?.comentarioEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3WxARDUgEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3WxARTUgEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setComentarioEngenharia">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3WxARjUgEfC2kOjxAoQ4kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3WxARzUgEfC2kOjxAoQ4kw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3WxASDUgEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3WxASTUgEfC2kOjxAoQ4kw" name="melhoriaInput.aprovacaoEngenharia" content="melhoriaInput?.aprovacaoEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3WxASjUgEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3WxASzUgEfC2kOjxAoQ4kw" type="JAVA_METHOD" expression="setAprovacaoEngenharia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nSqUQy-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nSq7UC-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nSq7US-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nSq7Uy-DEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nSq7Ui-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_y7gVuTUgEfC2kOjxAoQ4kw">
            <targetForm xmi:type="expression:Expression" xmi:id="_y7gVujUgEfC2kOjxAoQ4kw" name="AvaliacaoEngenhariaForm" content="49624c2a-a4df-4f03-ad43-3ed1f2104546" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_y7gVuDUgEfC2kOjxAoQ4kw">
            <inputs xmi:type="process:ContractInput" xmi:id="_3WxAEDUgEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_3WxAETUgEfC2kOjxAoQ4kw" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3WxAEjUgEfC2kOjxAoQ4kw" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3WxAEzUgEfC2kOjxAoQ4kw" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3WxAFDUgEfC2kOjxAoQ4kw" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3WxAFTUgEfC2kOjxAoQ4kw" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3WxAFjUgEfC2kOjxAoQ4kw" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3WxAFzUgEfC2kOjxAoQ4kw" name="comentarioEngenharia" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3WxAGDUgEfC2kOjxAoQ4kw" name="aprovacaoEngenharia" type="BOOLEAN" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_3WxAGTUgEfC2kOjxAoQ4kw" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_3WxAGjUgEfC2kOjxAoQ4kw" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_3WxAGzUgEfC2kOjxAoQ4kw" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_y7gVuzUgEfC2kOjxAoQ4kw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_fOYRkC9_EfCqJOVmptBMqg" name="Manutenção" actor="_VEfvIC-NEfC1UoIdMei-qg">
        <elements xmi:type="process:Task" xmi:id="_8sfYkC-DEfC1UoIdMei-qg" name="Avaliar Requisitos" outgoing="_APqkYC-EEfC1UoIdMei-qg" incoming="_8M-LAC-DEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8M884S-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8M884C-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8M884i-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_1YT7wDaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT7wTaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT7wjaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT7wzaTEfCfIviS7gC7ZA" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT7xDaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT7xTaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1YT7xjaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT7xzaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT7yDaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT7yTaTEfCfIviS7gC7ZA" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT7yjaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT7yzaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1YT7zDaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT7zTaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT7zjaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT7zzaTEfCfIviS7gC7ZA" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT70DaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT70TaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1YT70jaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT70zaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT71DaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT71TaTEfCfIviS7gC7ZA" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT71jaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT71zaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1YT72DaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT72TaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT72jaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT72zaTEfCfIviS7gC7ZA" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT73DaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT73TaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1YT73jaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT73zaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT74DaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT74TaTEfCfIviS7gC7ZA" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT74jaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT74zaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1YT75DaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT75TaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT75jaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT75zaTEfCfIviS7gC7ZA" name="melhoriaInput.comentarioEngenharia" content="melhoriaInput?.comentarioEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT76DaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT76TaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setComentarioEngenharia">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1YT76jaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT76zaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT77DaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT77TaTEfCfIviS7gC7ZA" name="melhoriaInput.aprovacaoEngenharia" content="melhoriaInput?.aprovacaoEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT77jaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT77zaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setAprovacaoEngenharia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1YT78DaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT78TaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT78jaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT78zaTEfCfIviS7gC7ZA" name="melhoriaInput.ordemServicoRequisitos" content="melhoriaInput?.ordemServicoRequisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT79DaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT79TaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setOrdemServicoRequisitos">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1YT79jaTEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1YT79zaTEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1YT7-DaTEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1YT7-TaTEfCfIviS7gC7ZA" name="melhoriaInput.requisitos" content="melhoriaInput?.requisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1YT7-jaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_1YT7-zaTEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setRequisitos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8M884y-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8M885C-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8M885S-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8M885y-DEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8M885i-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_8sf_qS-DEfC1UoIdMei-qg">
            <targetForm xmi:type="expression:Expression" xmi:id="_3QK1QDaTEfCfIviS7gC7ZA" name="AvaliacaoRequisitosForm" content="187a10bb-b802-4e13-b8bf-876af39f9aa4" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_8sf_qC-DEfC1UoIdMei-qg">
            <inputs xmi:type="process:ContractInput" xmi:id="_1YSGkDaTEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGkTaTEfCfIviS7gC7ZA" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGkjaTEfCfIviS7gC7ZA" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGkzaTEfCfIviS7gC7ZA" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGlDaTEfCfIviS7gC7ZA" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGlTaTEfCfIviS7gC7ZA" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGljaTEfCfIviS7gC7ZA" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGlzaTEfCfIviS7gC7ZA" name="comentarioEngenharia" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGmDaTEfCfIviS7gC7ZA" name="aprovacaoEngenharia" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGmTaTEfCfIviS7gC7ZA" name="ordemServicoRequisitos" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_1YSGmjaTEfCfIviS7gC7ZA" name="requisitos" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_1YTUsDaTEfCfIviS7gC7ZA" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_1YTUsTaTEfCfIviS7gC7ZA" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_1YTUsjaTEfCfIviS7gC7ZA" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_8sgmsC-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_HiElkC-FEfC1UoIdMei-qg" name="Implantar Melhoria" outgoing="_5QhLgC-EEfC1UoIdMei-qg" incoming="_y2P2wC-EEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_y2K-QS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_y2K-QC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_y2LlUC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_y2LlUS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_y2LlUi-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_y2LlUy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_y2MMYS-EEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_y2MMYC-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HiFzti-FEfC1UoIdMei-qg" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_IWW4QjUiEfC2kOjxAoQ4kw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HiFztS-FEfC1UoIdMei-qg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HiFzuC-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_1377kC-DEfC1UoIdMei-qg" name="PCM" actor="_WqMhoC-NEfC1UoIdMei-qg">
        <elements xmi:type="process:Task" xmi:id="_kV6v4DUhEfC2kOjxAoQ4kw" name="Gerar Ordem de Serviço - Requisitos" outgoing="_8M-LAC-DEfC1UoIdMei-qg" incoming="_4XxbEC-DEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4XwM8S-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4XwM8C-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4XwM8i-DEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_nIwy8zmrEfCHbIc87Mx5aw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nIwy9DmrEfCHbIc87Mx5aw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nIwy9TmrEfCHbIc87Mx5aw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nIwy9jmrEfCHbIc87Mx5aw" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nIwy9zmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nIwy-DmrEfCHbIc87Mx5aw" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_nIwy-TmrEfCHbIc87Mx5aw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nIwy-jmrEfCHbIc87Mx5aw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nIwy-zmrEfCHbIc87Mx5aw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nIwy_DmrEfCHbIc87Mx5aw" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nIwy_TmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nIwy_jmrEfCHbIc87Mx5aw" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_nIwy_zmrEfCHbIc87Mx5aw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nIwzADmrEfCHbIc87Mx5aw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nIwzATmrEfCHbIc87Mx5aw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nIwzAjmrEfCHbIc87Mx5aw" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nIwzAzmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nIwzBDmrEfCHbIc87Mx5aw" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_nIwzBTmrEfCHbIc87Mx5aw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nIwzBjmrEfCHbIc87Mx5aw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nIwzBzmrEfCHbIc87Mx5aw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nIwzCDmrEfCHbIc87Mx5aw" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nIwzCTmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nIwzCjmrEfCHbIc87Mx5aw" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_nIwzCzmrEfCHbIc87Mx5aw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nIwzDDmrEfCHbIc87Mx5aw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nIwzDTmrEfCHbIc87Mx5aw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nIwzDjmrEfCHbIc87Mx5aw" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nIwzDzmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nIwzEDmrEfCHbIc87Mx5aw" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_nIwzETmrEfCHbIc87Mx5aw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nIwzEjmrEfCHbIc87Mx5aw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nIwzEzmrEfCHbIc87Mx5aw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nIwzFDmrEfCHbIc87Mx5aw" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nIwzFTmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nIwzFjmrEfCHbIc87Mx5aw" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_nIwzFzmrEfCHbIc87Mx5aw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nIwzGDmrEfCHbIc87Mx5aw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nIwzGTmrEfCHbIc87Mx5aw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nIwzGjmrEfCHbIc87Mx5aw" name="melhoriaInput.comentarioEngenharia" content="melhoriaInput?.comentarioEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nIwzGzmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nIwzHDmrEfCHbIc87Mx5aw" type="JAVA_METHOD" expression="setComentarioEngenharia">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_nIwzHTmrEfCHbIc87Mx5aw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nIwzHjmrEfCHbIc87Mx5aw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nIwzHzmrEfCHbIc87Mx5aw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nIwzIDmrEfCHbIc87Mx5aw" name="melhoriaInput.aprovacaoEngenharia" content="melhoriaInput?.aprovacaoEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nIwzITmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nIwzIjmrEfCHbIc87Mx5aw" type="JAVA_METHOD" expression="setAprovacaoEngenharia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_nIwzIzmrEfCHbIc87Mx5aw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nIwzJDmrEfCHbIc87Mx5aw" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nIwzJTmrEfCHbIc87Mx5aw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nIwzJjmrEfCHbIc87Mx5aw" name="melhoriaInput.ordemServicoRequisitos" content="melhoriaInput?.ordemServicoRequisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nIwzJzmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nIwzKDmrEfCHbIc87Mx5aw" type="JAVA_METHOD" expression="setOrdemServicoRequisitos">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4XwM8y-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4XwM9C-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4XwM9S-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4Xw0AC-DEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4XwM9i-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kV7W-TUhEfC2kOjxAoQ4kw">
            <targetForm xmi:type="expression:Expression" xmi:id="_hLCa0DmsEfCHbIc87Mx5aw" name="GerarOrdemServicoResquisistosForm" content="708256b8-21a0-45c2-ba01-d859fbcb19ec" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kV7W-DUhEfC2kOjxAoQ4kw">
            <inputs xmi:type="process:ContractInput" xmi:id="_nIwL4DmrEfCHbIc87Mx5aw" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_nIwL4TmrEfCHbIc87Mx5aw" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nIwL4jmrEfCHbIc87Mx5aw" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nIwL4zmrEfCHbIc87Mx5aw" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nIwL5DmrEfCHbIc87Mx5aw" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nIwL5TmrEfCHbIc87Mx5aw" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nIwL5jmrEfCHbIc87Mx5aw" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nIwL5zmrEfCHbIc87Mx5aw" name="comentarioEngenharia" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nIwL6DmrEfCHbIc87Mx5aw" name="aprovacaoEngenharia" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nIwL6TmrEfCHbIc87Mx5aw" name="ordemServicoRequisitos" type="INTEGER" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_nIwy8DmrEfCHbIc87Mx5aw" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_nIwy8TmrEfCHbIc87Mx5aw" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_nIwy8jmrEfCHbIc87Mx5aw" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kV7W-zUhEfC2kOjxAoQ4kw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_SS3IMDUjEfC2kOjxAoQ4kw" name="Gerar Ordem de Serviço - Execucao" outgoing="_y2P2wC-EEfC1UoIdMei-qg" incoming="_wZaA4C-EEfC1UoIdMei-qg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wZYLsS-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wZYLsC-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wZYLsi-EEfC1UoIdMei-qg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Pca94DaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca94TaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca94jaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca94zaUEfCfIviS7gC7ZA" name="melhoriaInput.oQueFazer" content="melhoriaInput?.oQueFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca95DaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca95TaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setOQueFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca95jaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca95zaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca96DaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca96TaUEfCfIviS7gC7ZA" name="melhoriaInput.comoFazer" content="melhoriaInput?.comoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca96jaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca96zaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setComoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca97DaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca97TaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca97jaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca97zaUEfCfIviS7gC7ZA" name="melhoriaInput.ondeFazer" content="melhoriaInput?.ondeFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca98DaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca98TaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setOndeFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca98jaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca98zaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca99DaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca99TaUEfCfIviS7gC7ZA" name="melhoriaInput.descricaoFazer" content="melhoriaInput?.descricaoFazer" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca99jaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca99zaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setDescricaoFazer">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca9-DaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca9-TaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca9-jaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca9-zaUEfCfIviS7gC7ZA" name="melhoriaInput.comentarioGestor" content="melhoriaInput?.comentarioGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca9_DaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca9_TaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setComentarioGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca9_jaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca9_zaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca-ADaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca-ATaUEfCfIviS7gC7ZA" name="melhoriaInput.aprovacaoGestor" content="melhoriaInput?.aprovacaoGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca-AjaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca-AzaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setAprovacaoGestor">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca-BDaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca-BTaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca-BjaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca-BzaUEfCfIviS7gC7ZA" name="melhoriaInput.comentarioEngenharia" content="melhoriaInput?.comentarioEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca-CDaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca-CTaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setComentarioEngenharia">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca-CjaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca-CzaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca-DDaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca-DTaUEfCfIviS7gC7ZA" name="melhoriaInput.aprovacaoEngenharia" content="melhoriaInput?.aprovacaoEngenharia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca-DjaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca-DzaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setAprovacaoEngenharia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca-EDaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca-ETaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca-EjaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca-EzaUEfCfIviS7gC7ZA" name="melhoriaInput.ordemServicoRequisitos" content="melhoriaInput?.ordemServicoRequisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca-FDaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca-FTaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setOrdemServicoRequisitos">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca-FjaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca-FzaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca-GDaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca-GTaUEfCfIviS7gC7ZA" name="melhoriaInput.requisitos" content="melhoriaInput?.requisitos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca-GjaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca-GzaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setRequisitos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca-HDaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca-HTaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca-HjaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca-HzaUEfCfIviS7gC7ZA" name="melhoriaInput.analiseViabilidade" content="melhoriaInput?.analiseViabilidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca-IDaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca-ITaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setAnaliseViabilidade">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca-IjaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca-IzaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca-JDaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca-JTaUEfCfIviS7gC7ZA" name="melhoriaInput.aprovacaoViabilidade" content="melhoriaInput?.aprovacaoViabilidade" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca-JjaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca-JzaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setAprovacaoViabilidade">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca-KDaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca-KTaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca-KjaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca-KzaUEfCfIviS7gC7ZA" name="melhoriaInput.linkDocumentoFormalizado" content="melhoriaInput?.linkDocumentoFormalizado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca-LDaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca-LTaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setLinkDocumentoFormalizado">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Pca-LjaUEfCfIviS7gC7ZA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pca-LzaUEfCfIviS7gC7ZA" name="melhoria" content="melhoria" type="TYPE_VARIABLE" returnType="com.company.model.Melhoria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pca-MDaUEfCfIviS7gC7ZA" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pca-MTaUEfCfIviS7gC7ZA" name="melhoriaInput.ordemServicoExecucao" content="melhoriaInput?.ordemServicoExecucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Pca-MjaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pca-MzaUEfCfIviS7gC7ZA" type="JAVA_METHOD" expression="setOrdemServicoExecucao">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wZYLsy-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wZYLtC-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wZYLtS-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wZYLty-EEfC1UoIdMei-qg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wZYLti-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_SS4WVTUjEfC2kOjxAoQ4kw">
            <targetForm xmi:type="expression:Expression" xmi:id="_48m58DmpEfCHbIc87Mx5aw" name="GerarOrdemServicoExecucaoForm" content="0a63154b-793b-4f3a-bc0c-56a30e9a7147" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_SS4WVDUjEfC2kOjxAoQ4kw">
            <inputs xmi:type="process:ContractInput" xmi:id="_PcZIsDaUEfCfIviS7gC7ZA" name="melhoriaInput" type="COMPLEX" dataReference="melhoria" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZIsTaUEfCfIviS7gC7ZA" name="oQueFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvwDaUEfCfIviS7gC7ZA" name="comoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvwTaUEfCfIviS7gC7ZA" name="ondeFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvwjaUEfCfIviS7gC7ZA" name="descricaoFazer" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvwzaUEfCfIviS7gC7ZA" name="comentarioGestor" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvxDaUEfCfIviS7gC7ZA" name="aprovacaoGestor" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvxTaUEfCfIviS7gC7ZA" name="comentarioEngenharia" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvxjaUEfCfIviS7gC7ZA" name="aprovacaoEngenharia" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvxzaUEfCfIviS7gC7ZA" name="ordemServicoRequisitos" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvyDaUEfCfIviS7gC7ZA" name="requisitos" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvyTaUEfCfIviS7gC7ZA" name="analiseViabilidade" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvyjaUEfCfIviS7gC7ZA" name="aprovacaoViabilidade" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvyzaUEfCfIviS7gC7ZA" name="linkDocumentoFormalizado" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PcZvzDaUEfCfIviS7gC7ZA" name="ordemServicoExecucao" type="INTEGER" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_PcZvzTaUEfCfIviS7gC7ZA" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_PcZvzjaUEfCfIviS7gC7ZA" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_PcZvzzaUEfCfIviS7gC7ZA" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
              <inputNames>melhoriaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_SS4WVzUjEfC2kOjxAoQ4kw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Ytpj8C-JEfC1UoIdMei-qg" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1orjGDUfEfC2kOjxAoQ4kw" name="initMelhoria()" content="def melhoriaVar = new com.company.model.Melhoria()&#xD;&#xA;melhoriaVar.oQueFazer = melhoriaInput?.oQueFazer&#xD;&#xA;melhoriaVar.comoFazer = melhoriaInput?.comoFazer&#xD;&#xA;melhoriaVar.ondeFazer = melhoriaInput?.ondeFazer&#xD;&#xA;melhoriaVar.descricaoFazer = melhoriaInput?.descricaoFazer&#xD;&#xA;return melhoriaVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Melhoria">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_1orjGTUfEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_48bZmS9-EfCqJOVmptBMqg">
        <targetForm xmi:type="expression:Expression" xmi:id="_BOgMIzUfEfC2kOjxAoQ4kw" name="RequisicaoMelhoriaForm" content="74c45661-2694-4b96-af30-fb4c71806aa1" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_48bZmy9-EfCqJOVmptBMqg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_48bZnC9-EfCqJOVmptBMqg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VKRLgC-DEfC1UoIdMei-qg" target="_Wv7hwC-DEfC1UoIdMei-qg" source="_E81TkC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VKRLgS-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_VKRLgi-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZBq64C-DEfC1UoIdMei-qg" name="Reprovada" target="_b0KQoC-DEfC1UoIdMei-qg" source="_Wv7hwC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZBq64S-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZBq64i-DEfC1UoIdMei-qg" name="AprovarMelhoriaGestor()" content="melhoria.aprovacaoGestor == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_VhfHsDUgEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nSswgS-DEfC1UoIdMei-qg" name="Aprovada" target="_y7fHkDUgEfC2kOjxAoQ4kw" source="_Wv7hwC-DEfC1UoIdMei-qg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nSswgi-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_nSswgy-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pst74C-DEfC1UoIdMei-qg" target="_svB2UC-DEfC1UoIdMei-qg" source="_y7fHkDUgEfC2kOjxAoQ4kw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pst74S-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_pst74i-DEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rOnMcC-DEfC1UoIdMei-qg" name="Reprovada" target="_vKE8cC-DEfC1UoIdMei-qg" source="_svB2UC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rOnMcS-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_rOnMci-DEfC1UoIdMei-qg" name="aprovarMelhoraEngenhariaScript()" content="melhoria.aprovacaoEngenharia == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_R_tNkDUhEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4XxbEC-DEfC1UoIdMei-qg" name="Aprovada Engenharia" target="_kV6v4DUhEfC2kOjxAoQ4kw" source="_svB2UC-DEfC1UoIdMei-qg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4XxbES-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4XyCIC-DEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8M-LAC-DEfC1UoIdMei-qg" target="_8sfYkC-DEfC1UoIdMei-qg" source="_kV6v4DUhEfC2kOjxAoQ4kw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8M-LAS-DEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_8M-LAi-DEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_APqkYC-EEfC1UoIdMei-qg" target="_AkXpEC-EEfC1UoIdMei-qg" source="_8sfYkC-DEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_APqkYS-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_APrLcC-EEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OFHRQC-EEfC1UoIdMei-qg" target="_PEd1cC-EEfC1UoIdMei-qg" source="_AkXpEC-EEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OFHRQS-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OFH4UC-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YUkH0C-EEfC1UoIdMei-qg" name="Viável" target="_lt7VoC-EEfC1UoIdMei-qg" source="_PEd1cC-EEfC1UoIdMei-qg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YUku4C-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_YUku4S-EEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cvKq4i-EEfC1UoIdMei-qg" name="Inviável" target="_gRC2MC-EEfC1UoIdMei-qg" source="_PEd1cC-EEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cvLR8C-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_cvLR8S-EEfC1UoIdMei-qg" name="avaliaViabilidadeScript()" content="melhoria.aprovacaoViabilidade == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AZDDcDUiEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wZaA4C-EEfC1UoIdMei-qg" target="_SS3IMDUjEfC2kOjxAoQ4kw" source="_lt7VoC-EEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wZaA4S-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_wZan8C-EEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_y2P2wC-EEfC1UoIdMei-qg" target="_HiElkC-FEfC1UoIdMei-qg" source="_SS3IMDUjEfC2kOjxAoQ4kw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_y2Qd0C-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_y2Qd0S-EEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5QhLgC-EEfC1UoIdMei-qg" target="_5Qad0C-EEfC1UoIdMei-qg" source="_HiElkC-FEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5QhykC-EEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_5QhykS-EEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EvizkS-FEfC1UoIdMei-qg" target="_H-JdkC-FEfC1UoIdMei-qg" source="_5Qad0C-EEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EvjaoC-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_EvjaoS-FEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MH46IS-FEfC1UoIdMei-qg" target="_RV2lEC-LEfC1UoIdMei-qg" source="_H-JdkC-FEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MH5hMC-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_MH5hMS-FEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pr7ooS-FEfC1UoIdMei-qg" name="Sim" target="_P_uHUC-FEfC1UoIdMei-qg" source="_RV2lEC-LEfC1UoIdMei-qg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pr8PsC-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pr8PsS-FEfC1UoIdMei-qg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Sb8SIC-FEfC1UoIdMei-qg" target="_Sb514C-FEfC1UoIdMei-qg" source="_P_uHUC-FEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Sb8SIS-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Sb85MC-FEfC1UoIdMei-qg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VLbXMC-FEfC1UoIdMei-qg" name="Não" target="_YwpxcC-FEfC1UoIdMei-qg" source="_RV2lEC-LEfC1UoIdMei-qg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VLbXMS-FEfC1UoIdMei-qg"/>
        <condition xmi:type="expression:Expression" xmi:id="_VLbXMi-FEfC1UoIdMei-qg" name="AvaliarGanhosScript()" content="melhoria.ganhosAprovados == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ROH4QDUkEfC2kOjxAoQ4kw" name="melhoria" dataType="_48bZuS9-EfCqJOVmptBMqg" className="com.company.model.Melhoria"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_afCm0DUgEfC2kOjxAoQ4kw" target="_E81TkC-DEfC1UoIdMei-qg" source="_48aygy9-EfCqJOVmptBMqg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_afDN4DUgEfC2kOjxAoQ4kw"/>
        <condition xmi:type="expression:Expression" xmi:id="_afDN4TUgEfC2kOjxAoQ4kw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_48bZoC9-EfCqJOVmptBMqg" documentation="This is an example of actor that is mapped to any ACME users" name="Colaborador_actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_SeTI8C-NEfC1UoIdMei-qg" name="Gestor_actor"/>
      <actors xmi:type="process:Actor" xmi:id="_TsjEwC-NEfC1UoIdMei-qg" name="Engenharia_actor"/>
      <actors xmi:type="process:Actor" xmi:id="_VEfvIC-NEfC1UoIdMei-qg" name="Manutencao_actor"/>
      <actors xmi:type="process:Actor" xmi:id="_WqMhoC-NEfC1UoIdMei-qg" name="PCM_actor"/>
      <contract xmi:type="process:Contract" xmi:id="_48bZoS9-EfCqJOVmptBMqg">
        <inputs xmi:type="process:ContractInput" xmi:id="_1orjEDUfEfC2kOjxAoQ4kw" name="melhoriaInput" type="COMPLEX" dataReference="melhoria">
          <inputs xmi:type="process:ContractInput" xmi:id="_1orjETUfEfC2kOjxAoQ4kw" name="oQueFazer"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_1orjEjUfEfC2kOjxAoQ4kw" name="comoFazer"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_1orjEzUfEfC2kOjxAoQ4kw" name="ondeFazer"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_1orjFDUfEfC2kOjxAoQ4kw" name="descricaoFazer"/>
        </inputs>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_1orjFTUfEfC2kOjxAoQ4kw" expression="melhoriaInput?.oQueFazer != null" errorMessage="oQueFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_oQueFazer">
          <inputNames>melhoriaInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_1orjFjUfEfC2kOjxAoQ4kw" expression="melhoriaInput?.comoFazer != null" errorMessage="comoFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_comoFazer">
          <inputNames>melhoriaInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_1orjFzUfEfC2kOjxAoQ4kw" expression="melhoriaInput?.ondeFazer != null" errorMessage="ondeFazer is mandatory for Melhoria" name="mandatory_melhoriaInput_ondeFazer">
          <inputNames>melhoriaInput</inputNames>
        </constraints>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZoi9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZoy9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZpC9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZpS9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZpi9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZpy9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZqC9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZqS9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZqi9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZqy9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZrC9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZrS9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_48bZri9-EfCqJOVmptBMqg">
        <name xmi:type="expression:Expression" xmi:id="_48bZry9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_48bZsC9-EfCqJOVmptBMqg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_48bZsS9-EfCqJOVmptBMqg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_48bZsi9-EfCqJOVmptBMqg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_48bZsy9-EfCqJOVmptBMqg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_48bZtC9-EfCqJOVmptBMqg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_48bZtS9-EfCqJOVmptBMqg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_48bZti9-EfCqJOVmptBMqg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_48bZty9-EfCqJOVmptBMqg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_48bZuC9-EfCqJOVmptBMqg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_48bZuS9-EfCqJOVmptBMqg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_48bZui9-EfCqJOVmptBMqg" type="Process" element="_48aygC9-EfCqJOVmptBMqg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_48bZuy9-EfCqJOVmptBMqg" type="2007" element="_48aygS9-EfCqJOVmptBMqg">
      <children xmi:type="notation:DecorationNode" xmi:id="_48bZvC9-EfCqJOVmptBMqg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_48bZvS9-EfCqJOVmptBMqg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_48bZvi9-EfCqJOVmptBMqg" type="3007" element="_48aygi9-EfCqJOVmptBMqg">
          <children xmi:type="notation:DecorationNode" xmi:id="_48bZvy9-EfCqJOVmptBMqg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_48bZwC9-EfCqJOVmptBMqg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_48bZxC9-EfCqJOVmptBMqg" type="3002" element="_48aygy9-EfCqJOVmptBMqg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_48bZxS9-EfCqJOVmptBMqg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_48bZxi9-EfCqJOVmptBMqg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_48bZxy9-EfCqJOVmptBMqg" x="144" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_48bZyC9-EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_48bZyS9-EfCqJOVmptBMqg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_48bZyi9-EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_48bZyy9-EfCqJOVmptBMqg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_48bZzC9-EfCqJOVmptBMqg"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_eMbsYC9_EfCqJOVmptBMqg" type="3007" element="_eJCaIC9_EfCqJOVmptBMqg">
          <children xmi:type="notation:DecorationNode" xmi:id="_eMdhkC9_EfCqJOVmptBMqg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eMeIoC9_EfCqJOVmptBMqg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_E8498y-DEfC1UoIdMei-qg" type="3005" element="_E81TkC-DEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E86MEC-DEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E8499C-DEfC1UoIdMei-qg" x="99" y="104" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Wv9W8C-DEfC1UoIdMei-qg" type="3008" element="_Wv7hwC-DEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Wv9-AC-DEfC1UoIdMei-qg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Wv9-AS-DEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Wv9W8S-DEfC1UoIdMei-qg" x="308" y="102" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_b0MF0C-DEfC1UoIdMei-qg" type="3062" element="_b0KQoC-DEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_b0MF0i-DEfC1UoIdMei-qg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_b0MF0y-DEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b0MF0S-DEfC1UoIdMei-qg" x="498" y="115"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_P_vVcC-FEfC1UoIdMei-qg" type="3005" element="_P_uHUC-FEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_P_vVci-FEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P_vVcS-FEfC1UoIdMei-qg" x="1729" y="101" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Sb7EAC-FEfC1UoIdMei-qg" type="3003" element="_Sb514C-FEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Sb7rEC-FEfC1UoIdMei-qg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Sb7rES-FEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Sb7EAS-FEfC1UoIdMei-qg" x="1909" y="119"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eMbsYS9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eMcTcC9_EfCqJOVmptBMqg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eMcTcS9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eMeIoS9_EfCqJOVmptBMqg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eMcTci9_EfCqJOVmptBMqg" x="233" y="185"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_eiIPkC9_EfCqJOVmptBMqg" type="3007" element="_eiGaYC9_EfCqJOVmptBMqg">
          <children xmi:type="notation:DecorationNode" xmi:id="_eiJdsC9_EfCqJOVmptBMqg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eiJdsS9_EfCqJOVmptBMqg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_svCdYi-DEfC1UoIdMei-qg" type="3008" element="_svB2UC-DEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_svDEcS-DEfC1UoIdMei-qg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_svDEci-DEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_svDEcC-DEfC1UoIdMei-qg" x="472" y="121" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vKJ08C-DEfC1UoIdMei-qg" type="3062" element="_vKE8cC-DEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vKLDEC-DEfC1UoIdMei-qg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vKLDES-DEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vKJ08S-DEfC1UoIdMei-qg" x="669" y="128" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AkZeQC-EEfC1UoIdMei-qg" type="3005" element="_AkXpEC-EEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_AkaFUC-EEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AkZeQS-EEfC1UoIdMei-qg" x="858" y="117" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PEfDkC-EEfC1UoIdMei-qg" type="3008" element="_PEd1cC-EEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PEfDki-EEfC1UoIdMei-qg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PEfDky-EEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PEfDkS-EEfC1UoIdMei-qg" x="1065" y="128" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gREEUC-EEfC1UoIdMei-qg" type="3062" element="_gRC2MC-EEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gREEUi-EEfC1UoIdMei-qg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gRFScC-EEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gREEUS-EEfC1UoIdMei-qg" x="1072" y="21"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lt78vC-EEfC1UoIdMei-qg" type="3005" element="_lt7VoC-EEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lt8jwC-EEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lt78vS-EEfC1UoIdMei-qg" x="1165" y="128" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5QeIMC-EEfC1UoIdMei-qg" type="3017" element="_5Qad0C-EEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5QfWUC-EEfC1UoIdMei-qg" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5QfWUS-EEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5QeIMS-EEfC1UoIdMei-qg" x="1409" y="140"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_H-Krti-FEfC1UoIdMei-qg" type="3005" element="_H-JdkC-FEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_H-KruC-FEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_H-Krty-FEfC1UoIdMei-qg" x="1555" y="134" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ywq_ki-FEfC1UoIdMei-qg" type="3062" element="_YwpxcC-FEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_YwrmoC-FEfC1UoIdMei-qg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_YwrmoS-FEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ywq_ky-FEfC1UoIdMei-qg" x="1909" y="143"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RV3zMC-LEfC1UoIdMei-qg" type="3008" element="_RV2lEC-LEfC1UoIdMei-qg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_RV4aQC-LEfC1UoIdMei-qg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_RV4aQS-LEfC1UoIdMei-qg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RV3zMS-LEfC1UoIdMei-qg" x="1756" y="144" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y7gVvDUgEfC2kOjxAoQ4kw" type="3005" element="_y7fHkDUgEfC2kOjxAoQ4kw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_y7g8wDUgEfC2kOjxAoQ4kw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y7gVvTUgEfC2kOjxAoQ4kw" x="292" y="112" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eiIPkS9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eiIPki9_EfCqJOVmptBMqg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eiIPky9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eiJdsi9_EfCqJOVmptBMqg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eiIPlC9_EfCqJOVmptBMqg" x="319" y="418"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_fOaGwC9_EfCqJOVmptBMqg" type="3007" element="_fOYRkC9_EfCqJOVmptBMqg">
          <children xmi:type="notation:DecorationNode" xmi:id="_fObU4C9_EfCqJOVmptBMqg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_fObU4S9_EfCqJOVmptBMqg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_8sgmsS-DEfC1UoIdMei-qg" type="3005" element="_8sfYkC-DEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8shNwC-DEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8sgmsi-DEfC1UoIdMei-qg" x="707" y="102" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HiFzuS-FEfC1UoIdMei-qg" type="3005" element="_HiElkC-FEfC1UoIdMei-qg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HiGawC-FEfC1UoIdMei-qg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HiFzui-FEfC1UoIdMei-qg" x="1372" y="102" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_fOaGwS9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_fOaGwi9_EfCqJOVmptBMqg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_fOaGwy9_EfCqJOVmptBMqg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_fObU4i9_EfCqJOVmptBMqg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fOaGxC9_EfCqJOVmptBMqg" x="203" y="533"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_13-X0C-DEfC1UoIdMei-qg" type="3007" element="_1377kC-DEfC1UoIdMei-qg">
          <children xmi:type="notation:DecorationNode" xmi:id="_13--4C-DEfC1UoIdMei-qg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_13--4S-DEfC1UoIdMei-qg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_kV7W_DUhEfC2kOjxAoQ4kw" type="3005" element="_kV6v4DUhEfC2kOjxAoQ4kw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kV7W_jUhEfC2kOjxAoQ4kw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kV7W_TUhEfC2kOjxAoQ4kw" x="443" y="98" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SS4WWDUjEfC2kOjxAoQ4kw" type="3005" element="_SS3IMDUjEfC2kOjxAoQ4kw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SS4WWjUjEfC2kOjxAoQ4kw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SS4WWTUjEfC2kOjxAoQ4kw" x="1164" y="103" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_13-X0S-DEfC1UoIdMei-qg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_13-X0i-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_13-X0y-DEfC1UoIdMei-qg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_13--4i-DEfC1UoIdMei-qg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_13-X1C-DEfC1UoIdMei-qg" x="48" y="1000" width="1297" height="250"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_48bZzS9-EfCqJOVmptBMqg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_48bZzi9-EfCqJOVmptBMqg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_48bZzy9-EfCqJOVmptBMqg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_48bZ0C9-EfCqJOVmptBMqg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_48bZ0S9-EfCqJOVmptBMqg" width="2070" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_48bZ0i9-EfCqJOVmptBMqg"/>
    <edges xmi:type="notation:Connector" xmi:id="_VKRykC-DEfC1UoIdMei-qg" type="4001" element="_VKRLgC-DEfC1UoIdMei-qg" source="_E8498y-DEfC1UoIdMei-qg" target="_Wv9W8C-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VKTAsC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VKTAsS-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VKRykS-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VKRyki-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZBrh8C-DEfC1UoIdMei-qg" type="4001" element="_ZBq64C-DEfC1UoIdMei-qg" source="_Wv9W8C-DEfC1UoIdMei-qg" target="_b0MF0C-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZBrh8y-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZBrh9C-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZBrh8S-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZBrh8i-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Cp2YwC-NEfC1UoIdMei-qg" id="(0.23333333333333334,0.36666666666666664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nSt-oC-DEfC1UoIdMei-qg" type="4001" element="_nSswgS-DEfC1UoIdMei-qg" source="_Wv9W8C-DEfC1UoIdMei-qg" target="_y7gVvDUgEfC2kOjxAoQ4kw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nSulsC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nSulsS-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nSt-oS-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nSt-oi-DEfC1UoIdMei-qg" points="[0, 22, -24, -248]$[0, 240, -24, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pst74y-DEfC1UoIdMei-qg" type="4001" element="_pst74C-DEfC1UoIdMei-qg" source="_y7gVvDUgEfC2kOjxAoQ4kw" target="_svCdYi-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_psui8C-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_psui8S-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pst75C-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pst75S-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rOnzgC-DEfC1UoIdMei-qg" type="4001" element="_rOnMcC-DEfC1UoIdMei-qg" source="_svCdYi-DEfC1UoIdMei-qg" target="_vKJ08C-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rOnzgy-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rOnzhC-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rOnzgS-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rOnzgi-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4XyCIS-DEfC1UoIdMei-qg" type="4001" element="_4XxbEC-DEfC1UoIdMei-qg" source="_svCdYi-DEfC1UoIdMei-qg" target="_kV7W_DUhEfC2kOjxAoQ4kw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4XyCJC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4XypMC-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4XyCIi-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4XyCIy-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8M-LAy-DEfC1UoIdMei-qg" type="4001" element="_8M-LAC-DEfC1UoIdMei-qg" source="_kV7W_DUhEfC2kOjxAoQ4kw" target="_8sgmsS-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8M-yEC-DEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8M-yES-DEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8M-LBC-DEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8M-LBS-DEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_APrLcS-EEfC1UoIdMei-qg" type="4001" element="_APqkYC-EEfC1UoIdMei-qg" source="_8sgmsS-DEfC1UoIdMei-qg" target="_AkZeQC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_APrLdC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_APrLdS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_APrLci-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_APrLcy-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OFH4US-EEfC1UoIdMei-qg" type="4001" element="_OFHRQC-EEfC1UoIdMei-qg" source="_AkZeQC-EEfC1UoIdMei-qg" target="_PEfDkC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OFJGcC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OFJGcS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OFH4Ui-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OFH4Uy-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YUlV8C-EEfC1UoIdMei-qg" type="4001" element="_YUkH0C-EEfC1UoIdMei-qg" source="_PEfDkC-EEfC1UoIdMei-qg" target="_lt78vC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YUl9AC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YUl9AS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YUlV8S-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YUlV8i-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cvLR8i-EEfC1UoIdMei-qg" type="4001" element="_cvKq4i-EEfC1UoIdMei-qg" source="_PEfDkC-EEfC1UoIdMei-qg" target="_gREEUC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cvL5AC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cvL5AS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cvLR8y-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cvLR9C-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GQtKsC-NEfC1UoIdMei-qg" id="(0.2,0.7666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wZbPAC-EEfC1UoIdMei-qg" type="4001" element="_wZaA4C-EEfC1UoIdMei-qg" source="_lt78vC-EEfC1UoIdMei-qg" target="_SS4WWDUjEfC2kOjxAoQ4kw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wZbPAy-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wZbPBC-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wZbPAS-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wZbPAi-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_y2RE4C-EEfC1UoIdMei-qg" type="4001" element="_y2P2wC-EEfC1UoIdMei-qg" source="_SS4WWDUjEfC2kOjxAoQ4kw" target="_HiFzuS-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_y2Rr8C-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_y2STAC-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_y2RE4S-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y2RE4i-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5QiZoC-EEfC1UoIdMei-qg" type="4001" element="_5QhLgC-EEfC1UoIdMei-qg" source="_HiFzuS-FEfC1UoIdMei-qg" target="_5QeIMC-EEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5QjnwC-EEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5QjnwS-EEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5QiZoS-EEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5QiZoi-EEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Evjaoi-FEfC1UoIdMei-qg" type="4001" element="_EvizkS-FEfC1UoIdMei-qg" source="_5QeIMC-EEfC1UoIdMei-qg" target="_H-Krti-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EvjapS-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Evjapi-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Evjaoy-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EvjapC-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MH5hMi-FEfC1UoIdMei-qg" type="4001" element="_MH46IS-FEfC1UoIdMei-qg" source="_H-Krti-FEfC1UoIdMei-qg" target="_RV3zMC-LEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MH6IQC-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MH6IQS-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MH5hMy-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MH5hNC-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pr8Psi-FEfC1UoIdMei-qg" type="4001" element="_Pr7ooS-FEfC1UoIdMei-qg" source="_RV3zMC-LEfC1UoIdMei-qg" target="_P_vVcC-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pr82wC-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pr82wS-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pr8Psy-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pr8PtC-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sb9gQC-FEfC1UoIdMei-qg" type="4001" element="_Sb8SIC-FEfC1UoIdMei-qg" source="_P_vVcC-FEfC1UoIdMei-qg" target="_Sb7EAC-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sb-uYC-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sb-uYS-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sb9gQS-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Sb9gQi-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VLb-QC-FEfC1UoIdMei-qg" type="4001" element="_VLbXMC-FEfC1UoIdMei-qg" source="_RV3zMC-LEfC1UoIdMei-qg" target="_Ywq_ki-FEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VLb-Qy-FEfC1UoIdMei-qg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VLb-RC-FEfC1UoIdMei-qg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VLb-QS-FEfC1UoIdMei-qg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VLb-Qi-FEfC1UoIdMei-qg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_afDN4jUgEfC2kOjxAoQ4kw" type="4001" element="_afCm0DUgEfC2kOjxAoQ4kw" source="_48bZxC9-EfCqJOVmptBMqg" target="_E8498y-DEfC1UoIdMei-qg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_afDN5TUgEfC2kOjxAoQ4kw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_afDN5jUgEfC2kOjxAoQ4kw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_afDN4zUgEfC2kOjxAoQ4kw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_afDN5DUgEfC2kOjxAoQ4kw" points="[-19, 3, 4, -329]$[-22, 325, 1, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_afEcADUgEfC2kOjxAoQ4kw" id="(1.0,0.8666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_afEcATUgEfC2kOjxAoQ4kw" id="(0.4666666666666667,0.1)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
